Update invariants
ajna-finance/ecosystem-coordination pull request #106
Opened 2023-06-07 22:22 UTC by MikeHathaway

# Description of change
## High level
* Refactor invariant harness:
  * Create new scenarios subdirectory containing the actual test files.
  * Create new abstract contracts containing internal invariant functions enabling usage across multiple scenarios.

2023-06-10 04:13 UTC, EdNoepel reviewed
I noticed tests mix assertions with `require` statements.  Is this intentional/desirable?

2023-06-10 04:13 UTC, EdNoepel commented on test/invariants/base/DistributionPeriodInvariants.sol
> +                "invariant DP3: A distribution's fundsAvailablePrev should be equal to 3% of the treasurie's balance at the block `startNewDistributionPeriod()` is called"
nit: spelling `treasury's`

2023-06-12 05:25 UTC, prat-gpt commented on test/invariants/base/DistributionPeriodInvariants.sol
> +            if (i == 0) {
Can we start looping from 1 instead of 0 as we just `continue` if `i = 0`?

2023-06-12 05:42 UTC, prat-gpt commented on test/invariants/base/DistributionPeriodInvariants.sol
> +            if (i == 1) {
I think this condition is redundant as if `i = 1` or `prevDistributionId = 0`, then `surplus = 0`, i.e `expectedTreasury =  state.treasuryBeforeStart`

2023-06-13 01:50 UTC, MikeHathaway commented on test/invariants/base/DistributionPeriodInvariants.sol
> +                "invariant DP3: A distribution's fundsAvailablePrev should be equal to 3% of the treasurie's balance at the block `startNewDistributionPeriod()` is called"
Updated

2023-06-13 01:50 UTC, MikeHathaway commented on test/invariants/base/DistributionPeriodInvariants.sol
> +            if (i == 0) {
Updated

2023-06-13 02:33 UTC, MikeHathaway commented
> I noticed tests mix assertions with `require` statements. Is this intentional/desirable?

I updated this in a few places, but I didn't want to make too many significant changes since it's hard to track with the moved files. Asserts are used in a lot of places where there isn't an explicit invariant, or if there's multiple ways to check the same invariant - having multiple requires with duplicate invariant strings seemed messy.

2023-06-13 02:54 UTC, MikeHathaway commented on test/invariants/base/DistributionPeriodInvariants.sol
> +            if (i == 1) {
Removed

2023-06-13 13:05 UTC, prat-gpt approved these changes
LGTM!

2023-06-13 15:03 UTC, grandizzy requested changes
Couple of commentes re using assert instead require and commented code

2023-06-13 15:03 UTC, grandizzy commented on test/invariants/base/FundingInvariants.sol
> +                assertEq(fundingVotesReceived, 0);
better to use `require` and a meaningful reason / specify failing invariant

2023-06-13 15:03 UTC, grandizzy commented on test/invariants/base/FundingInvariants.sol
> +        assertTrue(topTenProposals.length <= 10);
better to use `require` and a meaningful reason / specify failing invariant

2023-06-13 15:03 UTC, grandizzy commented on test/invariants/base/FundingInvariants.sol
> +            assertEq(sumOfSquares, votingPower - remainingVotingPower);
better to use `require` and a meaningful reason / specify failing invariant

2023-06-13 15:03 UTC, grandizzy commented on test/invariants/base/FundingInvariants.sol
> +                assertTrue(numberOfProposalsVotedOn == fundingVotesCast.length);
don't think these needs to be `require` as they're not testing any invariants but wanted to flag it

2023-06-13 15:03 UTC, grandizzy commented on test/invariants/scenarios/FundingInvariant.t.sol
> +        // _standardHandler.logProposalSummary();
should these be uncommented?

2023-06-13 15:03 UTC, grandizzy commented on test/invariants/scenarios/MultipleDistributionInvariant.t.sol
> +        // _standardHandler.logProposalSummary();
can these be removed?

2023-06-13 15:03 UTC, grandizzy commented on test/invariants/scenarios/ScreeningInvariant.t.sol
> +        // _standardHandler.logProposalSummary();
can this be removed?

2023-06-13 17:58 UTC, MikeHathaway commented
> Couple of commentes re using assert instead require and commented code

The commented code is helpful for debugging - it still needs to be there, but it can be sometimes too much logged information in certain scenarios. I was planning on cleaning up how we handle this logging in a subsequent PR.

2023-06-13 17:58 UTC, MikeHathaway commented on test/invariants/base/FundingInvariants.sol
> +            assertEq(sumOfSquares, votingPower - remainingVotingPower);
Replaced

2023-06-13 17:59 UTC, MikeHathaway commented on test/invariants/base/FundingInvariants.sol
> +        assertTrue(topTenProposals.length <= 10);
Replaced

2023-06-13 17:59 UTC, MikeHathaway commented on test/invariants/base/FundingInvariants.sol
> +                assertTrue(numberOfProposalsVotedOn == fundingVotesCast.length);
Replaced

2023-06-13 18:20 UTC, grandizzy approved these changes
lgtm

2023-06-13 18:21 UTC, merged