Updates:
ajna-finance/ecosystem-coordination pull request #2
Opened 2022-08-15 11:25 UTC by grandizzy

- add Makefile
- add GH actions run tests with gas report and coverage step
- Ajna token:
  - update Solidity to 0.8.15
  - add guard against sending tokens to token contract
  - initialize in token contract constructor
- Ajna token tests

2022-08-15 13:40 UTC, EdNoepel approved these changes
LGTM

2022-08-15 20:54 UTC, MikeHathaway commented on src/Token.sol
> -    }
I think it's still recommended to call `_disableInitializers()` in the constructor() without the `initialize()` there

2022-08-15 21:59 UTC, MikeHathaway commented
Updated my PR with the fix for interacting with the upgradeable token in the forge tests here: https://github.com/ajna-finance/ajna-token/pull/1

2022-08-15 22:00 UTC, MikeHathaway requested changes
Tests look good, but this should be rebased on the other PR following merge

2022-08-16 09:00 UTC, closed without merging

2022-08-16 09:02 UTC, grandizzy commented
> Tests look good, but this should be rebased on the other PR following merge

I created PR https://github.com/ajna-finance/ajna-token/pull/3 on top of `token-tests` branch to add only missing things from this PR