Implement the Standard Proposal Mechanism of the Growth Coordination Fund
ajna-finance/ecosystem-coordination pull request #20
Opened 2022-09-05 15:46 UTC by MikeHathaway

Initial implementation of Ajna Growth Coordination Fund Standard Proposal Mechanism, with associated tests. Inherits from OpenZeppeling Governor with the GovernorVotesQuorumFraction extension to enable compatibility with existing governance tooling such as tally.xyz.

<br>
*IMPLEMENTED*

- Override `propose()`, `_getVotes` and `_castVote` to ensure all calls to the growth fund governor logic flow through the screening -> funding process.
- Implement insertion-sort algorithm for determine top 10 vote receiving proposals in the one-stage-one-vote screening stage.
- Implementation of QV based funding stage with a `checkSlate` method used to verify off-chain solutions to the knapsack problem presented by the optimal set of proposal to fund.
- Override `execute()` to ensure only proposals that went through the Distribution cycle can be executed.
- Add structs and mappings to enable storage and access of information required to track proposals and distributions over time.
- Use OZ.checkpoints to allow `distributionId` to be retrieved based upon a given `block.number`

<br>
*TODO*

- Implement the Extraordinary Funding Mechanism
- Split GrowthFund.sol into separate abstract contracts for standard and extraordinary funding mechanisms.
- Implement Proposal state enum to maintain compatibility with Tally.xyz expectation: https://docs.tally.xyz/user-guides/tally-contract-compatibility/openzeppelin-governor
- Expand README for GrowthFund logic

2022-10-24 19:18 UTC, ith-harvey commented on script/AjnaToken.s.sol
> +import { AjnaToken } from "../src/AjnaToken.sol";
I'm a big fan of us sharing our design patterns... accross our products. I propose we match our `contracts` repo and simply perform the imports without specifying the contracts...

Thoughts?

2022-10-24 19:21 UTC, MikeHathaway commented on script/AjnaToken.s.sol
> +import { AjnaToken } from "../src/AjnaToken.sol";
That sounds good to me. This was written before we switched the `contracts` repo over, but can easily change this as well.

2022-10-24 19:36 UTC, EdNoepel reviewed
No issues.

2022-10-24 19:36 UTC, EdNoepel commented on src/GrowthFund.sol
> +     * @notice Start a new Distribution Period and reset appropiate state.
sp: appropriate

2022-10-24 19:36 UTC, EdNoepel commented on src/GrowthFund.sol
> +    function execute(address[] memory targets, uint256[] memory values, bytes[] memory calldatas, bytes32 descriptionHash) public payable override(Governor) returns (uint256) {
The OZ superclass' `_afterExecute` method clears the proposal _after_ execution.  But do we need a reentrancy check to ensure the proposal cannot itself call `execute`?

2022-10-24 19:36 UTC, EdNoepel commented on src/GrowthFund.sol
> +     * @dev    Snapshot checks are built into this function to ensure accurate power is returned regardless of the caller.
I'm having trouble understanding what _number of votes available_ means.  Superclass calls this the _voting weight_.  Perhaps adding a `@returns` natspec could clarify?

2022-10-24 19:36 UTC, EdNoepel commented on src/GrowthFund.sol
> +     * @notice Required ovveride; not currently used due to divergence in voting logic.
sp: override

2022-10-24 19:36 UTC, EdNoepel commented on src/GrowthFund.sol
> +        if (keccak256(stage_) == keccak256(bytes("Screening"))) {
I assume string is better than an enum because the superclass takes bytes, and because it produces a better hash?

2022-10-24 19:36 UTC, EdNoepel commented on test/GrowthFundTestHelper.sol
> +    function _loadProposalSlateJSON(string memory filePath) internal returns (IGrowthFund.Proposal[] memory) {
From where is this called?

2022-10-24 20:11 UTC, MikeHathaway commented on src/GrowthFund.sol
> +     * @notice Required ovveride; not currently used due to divergence in voting logic.
Updated

2022-10-24 20:11 UTC, MikeHathaway commented on src/GrowthFund.sol
> +     * @notice Start a new Distribution Period and reset appropiate state.
Updated

2022-10-24 20:26 UTC, MikeHathaway commented on test/GrowthFundTestHelper.sol
> +    function _loadProposalSlateJSON(string memory filePath) internal returns (IGrowthFund.Proposal[] memory) {
This was originally part of a test that I removed. I was attempting to use Foundry's new `parseJson` functionality, but ran into issues decoding large `int` values. I decided to leave this helper function in so we could revisit fixture based testing following upgrades to foundry's json parser. Reference is here: https://book.getfoundry.sh/cheatcodes/parse-json?highlight=parseJson#parsejson

That being said, I'd be open to removing this function.

2022-10-24 20:36 UTC, ith-harvey commented on src/interfaces/IGrowthFund.sol
> +interface IGrowthFund {
Propose we change the name of the repository, respective contracts, variabes and methods it may apply to from `Growth Coordination` -> `Grant Coordination` as it was changed in the v10 spec

2022-10-24 20:36 UTC, ith-harvey commented on src/GrowthFund.sol
> +    uint256 public globalBudgetConstraint = Maths.wdiv(Maths.wad(2), Maths.wad(100));
Shouldn't this be a `constant`?

2022-10-24 20:36 UTC, ith-harvey commented on src/GrowthFund.sol
> +    uint256 public constant DISTRIBUTION_PERIOD_LENGTH = 648000; // 90 days
`constant`?

2022-10-24 20:36 UTC, ith-harvey commented on src/GrowthFund.sol
> +    function propose(
Where does the Natspec for this func live?

2022-10-24 20:37 UTC, MikeHathaway commented on src/GrowthFund.sol
> +    function execute(address[] memory targets, uint256[] memory values, bytes[] memory calldatas, bytes32 descriptionHash) public payable override(Governor) returns (uint256) {
That's a good call out. I don't think reetrancy should be possible here since the `checkProposal` modifier looks at the function selector and restricts it to just `transfer()`, so any proposal that contained the calldata for reentering execute should fail at the proposal creation stage. That being said, I don't think it would hurt too much to add a nonreentrant modifier to this method, and I can add a test around reentrancy in case there's a way to hide the `execute()` calldata.

I added OpenZeppelin `ReentrancyGuard` to better protect the `execute()` method.

2022-10-24 20:49 UTC, MikeHathaway commented on src/GrowthFund.sol
> +    uint256 public globalBudgetConstraint = Maths.wdiv(Maths.wad(2), Maths.wad(100));
Updated

2022-10-24 20:49 UTC, MikeHathaway commented on src/GrowthFund.sol
> +    uint256 public constant DISTRIBUTION_PERIOD_LENGTH = 648000; // 90 days
What's the question here?

2022-10-24 20:49 UTC, MikeHathaway commented on src/GrowthFund.sol
> +    function propose(
Updated

2022-10-24 20:50 UTC, MikeHathaway commented on src/GrowthFund.sol
> +     * @dev    Snapshot checks are built into this function to ensure accurate power is returned regardless of the caller.
I've updated the natspec accordingly. Let me know if this is more clear.

2022-10-24 20:51 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        if (keccak256(stage_) == keccak256(bytes("Screening"))) {
Yeah the bytes parameter is available and required here, so it enables me to avoid the additional computation of taking the `blockNumber` and using that to determine the appropriate enum value. Would also likely need to mix the two anyways in order to determine if the votes are part of the standard mechanism, or the extraordinary mechanism.

2022-10-25 10:02 UTC, grandizzy requested changes
Nice work! Please see my comments, I am yet to understand OZ's governance contract, will get some more into these and come back with additional questions

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +    uint256 public constant globalBudgetConstraint = 20000000000000000;
I suggest making constants internal

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +        extraordinaryFundingBaseQuorum = 50; // initialize base quorum percentrage required for extraordinary funding to 50%
shouldn't `extraordinaryFundingBaseQuorum`,  `votingTokenAddress` and `ajnaToken` be immutables instead setting them in constructor? Also I don't think we need both  `votingTokenAddress` and `ajnaToken` as  `votingTokenAddress` can be easily obtained if needed as `address(ajnaToken)`. Instead importing `import "./AjnaToken.sol";` we can just import the `IERC20` interface, no need to work with the implementation.

So instead `AjnaToken  internal ajnaToken;` we can have `address immutable ajnaAddress = 0x9a96ec9B57Fb64FbC60B423d1f4da7691Bd35079` and use `IERC20(ajnaAddress).balanceOf` or so

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +     * @dev    Screening period is 80 days, funding period is 10 days. Total distributin is 90 days.
NIT typo `Total distribution is 90 days`

2022-10-25 10:02 UTC, grandizzy commented on src/interfaces/IGrowthFund.sol
> +        uint256 startBlock;         // block number of the quarterly distrubtions start
NIT typo `// block number of the quarterly distributions start` same for next line

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +        uint256 currentDistributionId = getDistributionId();
recommend not to call external / public function here (as it requires more gas) but inline `_distributionIdCheckpoints.latest()`

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +        (uint256 prevId, uint256 newId) = _distributionIdCheckpoints.push(currentDistributionId + 1);
since `prevId` is not used this can be changed to `(, uint256 newId)` or better IMO with named params
`function _setNewDistributionId() private returns (uint256 newId_)` then `(, newId_) = _distributionIdCheckpoints.push(currentDistributionId + 1);` and get rid of return statement

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +        uint256 newDistributionId = getDistributionId();
same as above, don't call external function here to get `newDistributionId`

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +        newDistributionPeriod.id =  newDistributionId;
NIT equals alignments

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +        return newDistributionPeriod.id;
gas cost is more efficient to use named params, e.g.

`function startNewDistributionPeriod() external returns (uint256 newDistributionId_) {`

then `newDistributionId_ = _distributionIdCheckpoints.latest();` and `newDistributionPeriod.id =  newDistributionId_;` and get rid of return statement

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +        _setNewDistributionId();
since we're reading and incrementing `currentDistributionId` already in `_setNewDistributionId()` I recommend changing signature and returning the new distribution id from `_setNewDistributionId` and delete next line / save gas (e.g. if using named return var from `startNewDistributionPeriod` function: `newDistributionId_ = _setNewDistributionId()`)

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +    function _fundingVote(Proposal storage proposal_, address account_, QuadraticVoter storage voter_, int256 budgetAllocation_) internal returns (uint256) {
`voter_.budgetRemaining` and `proposal_.qvBudgetAllocated` are both `int256` so we can get rid of `int256 allocationUsed = 0;` and use function argument `int256 budgetAllocation_`, e.g. this block can be rewritten as 
```
        voter_.budgetRemaining      += budgetAllocation_;
        proposal_.qvBudgetAllocated += budgetAllocation_;
```
then `emit VoteCast(account_, proposal_.proposalId, budgetAllocation_, "");` - I think is better to have `VoteCast` `weight` of type int256 and get rid of `support` too (as we'll see if it was against or in support by the sign of `weight` / `budgetAllocation_`)

No need to return something from this function, I'd say function name can be `_fundVote`

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +            int256 budgetAllocation = abi.decode(params_, (int256));
use named param so this becomes `budgetAllocation_ = abi.decode(params_, (int256));` and remove return statement (see also comment re renaming `_fundingVote` to `_funcVote` and removing returned value)

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +        uint256 distributionId = getDistributionId();
use internal call here to retrieve distribution id

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +                index = i;
since we found the index, shouldn't we break loop and exit here?

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +        for (int i = 0; i < int(array.length);) {
since `array` is of type storage `array.length` is costly as it will load storage on each iteration, we should `uint256 arrayLength = array.length` and then `for (int i = 0; i < int(arrayLength);) {` recommend explicit `int256` instead aliased `int`

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +    function _findInArray(uint256 proposalId, Proposal[] storage array) internal view returns (int256 index) {
let's use returned param naming `index_` instead `index`. I recommend changing function name to something more specific like instead `_findInArray` to `_findProposalIndex`?

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +                _updateFundedSlate(fundedProposals_, currentDistribution, newSlateHash);
instead passing the entire storage obj I suggest passing the current distribution id only and update the `fundedSlateHash` outside  `_updateFundedSlate`, this should save gas afaik

Also IMO this block can be rewritten with a named `newTopSlate_` variable as

```
        newTopSlate_ = currentSlateHash == 0  ||
            (currentSlateHash != 0 && (sum > _sumBudgetAllocated(fundedProposalSlates[distributionId_][currentSlateHash])));
        if (newTopSlate_) {
            _updateFundedSlate(fundedProposals_, currentDistribution_.id, newSlateHash);
            currentDistribution.fundedSlateHash = newSlateHash;
        }
```

and not have any kind of return statements. Since `_updateFundedSlate` is only used here we can remove it entirely and iterate inline / merge with for at line 252 somehow so we iterate only once the `fundedProposals_`?

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +        uint256 gbc = maximumQuarterlyDistribution();
let's use an internal function here

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +        if (block.number <= currentDistribution.endBlock || block.number > currentDistribution.endBlock + 50400) {
let's express `50400` as `14 hours` for better readability. which beg the question why 14 hours?

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +        bytes32 newSlateHash = getSlateHash(fundedProposals_);
better `keccak256(abi.encode(proposals_))` inline instead calling the external function `getSlateHash`

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +        uint256 proposalId = hashProposal(targets, values, calldatas, keccak256(bytes(description)));
better inline `uint256(keccak256(abi.encode(targets, values, calldatas, descriptionHash)));` than calling external `hashProposal` function

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +        newProposal.distributionId = getDistributionId();
let's use `_distributionIdCheckpoints.latest()`

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +        uint256 proposalId = hashProposal(targets, values, calldatas, descriptionHash);
better inline `uint256(keccak256(abi.encode(targets, values, calldatas, descriptionHash)));` than calling external `hashProposal` function. I suggest using named variable `proposalId_` as well and get rid of return statement

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +    function execute(address[] memory targets, uint256[] memory values, bytes[] memory calldatas, bytes32 descriptionHash) public payable override(Governor) nonReentrant returns (uint256) {
NIT function arguments should be named like `targets_`, `values_` etc.

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +        address[] memory targets,
NIT function arguments should be named like `targets_`, `values_` etc.

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +        if (_findInArray(proposalId, fundedProposalSlates[proposal.distributionId][distributions[proposal.distributionId].fundedSlateHash]) == -1) {
I find these lines a little bit hard to read, I recommend 
```
uint256 distributionId = proposal.distributionId;
if (_findInArray(proposalId, fundedProposalSlates[distributionId][distributions[distributionId].fundedSlateHash]) == -1) {\
```
or something easier to read

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +        QuarterlyDistribution memory currentDistribution = distributions[getDistributionId()];
let's avoid calling external `getDistributionId()` here. Also down the code we're calling this again in `Proposal[] storage currentTopTenProposals = topTenProposals[getDistributionId()];` this can be reused

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +        uint256 screeningPeriodEndBlock = getScreeningPeriodEndBlock(currentDistribution);
let's `currentDistribution.endBlock - 20 hours` instead  calling external `getScreeningPeriodEndBlock` (change 72000 to hours in this function as well).

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +            return _screeningVote(currentTopTenProposals, account_, proposal, votes);
since `_screeningVote` is called only here let's just pass the `distributionId` param instead `Proposal[] storage currentTopTenProposals` and load `topTenProposals[distributionId]` in `_screeningVote` body

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +        require(topTenProposals[getDistributionId()].length <= 10 && topTenProposals[getDistributionId()].length > 0, "CV:LIST_MALFORMED");
use custom error here. We already have the `currentTopTenProposals_` loaded from storage, no need to reload it here (twice). see comments within `_castVote` function, we can pass `distributionId` from `_castVote` function (instead `Proposal[] storage currentTopTenProposals_`) and load from storage in this function. then reuse to check its length (and load length only once)

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +        require(topTenProposals[getDistributionId()].length <= 10 && topTenProposals[getDistributionId()].length > 0, "CV:LIST_MALFORMED");
isn't there a way to ensure array is not > 10, that is to enforce a fixed size of 10?

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +                voter.votingWeight = Maths.wpow(super._getVotes(account_, getScreeningPeriodEndBlock(currentDistribution) - 33, ""), 2);
let's `currentDistribution.endBlock - 20 hours` instead  calling external `getScreeningPeriodEndBlock`

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +                return Maths.wpow(super._getVotes(account_, getScreeningPeriodEndBlock(currentDistribution) - 33, ""), 2);
let's `currentDistribution.endBlock - 20 hours` instead  calling external `getScreeningPeriodEndBlock`

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +        if (hasVoted(proposal_.proposalId, account_)) revert AlreadyVoted();
can be simplified to `if (hasScreened[account_]) revert AlreadyVoted();`

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +        if (currentTopTenProposals_.length < 10 && indexInArray == -1) {
read length only once and reuse it on line 496 where `else if(currentTopTenProposals_[currentTopTenProposals_.length - 1].votesReceived`

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +                return uint256(voter.budgetRemaining);
I wonder if a budget can go negative or only to 0 and if we can keep it as uint256 instead int256 and do the casts all over the code?

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +    function hasVoted(uint256, address account_) public view override(IGovernor) returns (bool) {
I suggest using named variable and simplifying here to `hasVoted = hasScreened[account_];` `return hasScreened[account_]` is fine too :)

2022-10-25 10:02 UTC, grandizzy commented on src/GrowthFund.sol
> +import "@oz/token/ERC20/IERC20.sol";
doesn't seem we need to import this one?

2022-10-25 10:05 UTC, grandizzy requested changes

2022-10-25 10:05 UTC, grandizzy commented on src/GrowthFund.sol
> +    uint256 public constant DISTRIBUTION_PERIOD_LENGTH = 648000; // 90 days
better write it as `DISTRIBUTION_PERIOD_LENGTH = 90 days`

2022-10-25 16:31 UTC, MikeHathaway commented on src/GrowthFund.sol
> +    uint256 public constant DISTRIBUTION_PERIOD_LENGTH = 648000; // 90 days
This doesn't work for block numbers, only timestamps

2022-10-25 16:31 UTC, MikeHathaway commented on src/GrowthFund.sol
> +import "@oz/token/ERC20/IERC20.sol";
removed

2022-10-25 16:33 UTC, MikeHathaway commented on src/GrowthFund.sol
> +    function hasVoted(uint256, address account_) public view override(IGovernor) returns (bool) {
Updated

2022-10-25 16:35 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        if (currentTopTenProposals_.length < 10 && indexInArray == -1) {
Updated

2022-10-25 16:35 UTC, grandizzy commented on src/GrowthFund.sol
> +    uint256 public constant DISTRIBUTION_PERIOD_LENGTH = 648000; // 90 days
👍

2022-10-25 16:36 UTC, MikeHathaway commented on src/interfaces/IGrowthFund.sol
> +        uint256 startBlock;         // block number of the quarterly distrubtions start
Updated

2022-10-25 16:36 UTC, MikeHathaway commented on src/GrowthFund.sol
> +     * @dev    Screening period is 80 days, funding period is 10 days. Total distributin is 90 days.
Updated

2022-10-25 16:37 UTC, MikeHathaway commented on src/GrowthFund.sol
> +    uint256 public constant globalBudgetConstraint = 20000000000000000;
Updated

2022-10-25 16:39 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        uint256 currentDistributionId = getDistributionId();
Updated

2022-10-25 16:42 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        if (hasVoted(proposal_.proposalId, account_)) revert AlreadyVoted();
Updated

2022-10-25 16:48 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        (uint256 prevId, uint256 newId) = _distributionIdCheckpoints.push(currentDistributionId + 1);
Updated

2022-10-25 16:48 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        uint256 newDistributionId = getDistributionId();
Removed in favor of using the return value from `_setNewDistributionId();`

2022-10-25 16:48 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        newDistributionPeriod.id =  newDistributionId;
Updated

2022-10-25 17:06 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        uint256 distributionId = getDistributionId();
Updated to access from `proposal_.distributionId` instead

2022-10-25 17:10 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        return newDistributionPeriod.id;
Updated

2022-10-25 17:10 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        _setNewDistributionId();
Updated

2022-10-25 17:13 UTC, MikeHathaway commented on src/GrowthFund.sol
> +                index = i;
added `break`

2022-10-25 17:15 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        for (int i = 0; i < int(array.length);) {
used variable for array length and changed function signature from `storage` to `memory`. Also changed this to a `pure` function (both of which resulted in substantial gas savings).

Following those updates, using a variable for array length actually increases gas costs

2022-10-25 17:16 UTC, MikeHathaway commented on src/GrowthFund.sol
> +    function _findInArray(uint256 proposalId, Proposal[] storage array) internal view returns (int256 index) {
Updated

2022-10-25 17:23 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        if (block.number <= currentDistribution.endBlock || block.number > currentDistribution.endBlock + 50400) {
`hours` also works only with timestamps. This is `50400 blocks` which is equivalent to 1 week given the newly consistent 12 seconds per block post merge. We offer a 1 week "Challenge" period where anyone can offer competing slates with a more optimal solution for funding distribution

2022-10-25 17:26 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        newProposal.distributionId = getDistributionId();
Updated

2022-10-25 17:28 UTC, MikeHathaway commented on src/GrowthFund.sol
> +    function execute(address[] memory targets, uint256[] memory values, bytes[] memory calldatas, bytes32 descriptionHash) public payable override(Governor) nonReentrant returns (uint256) {
Updated

2022-10-25 17:28 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        address[] memory targets,
Updated

2022-10-25 17:33 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        require(topTenProposals[getDistributionId()].length <= 10 && topTenProposals[getDistributionId()].length > 0, "CV:LIST_MALFORMED");
I'm not sure what you're asking here - we could likely remove this `require` statement entirely as it should be enforced previously, but there's a hard requirement that <= 10 proposals make it through the screening stage.

2022-10-25 17:39 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        if (_findInArray(proposalId, fundedProposalSlates[proposal.distributionId][distributions[proposal.distributionId].fundedSlateHash]) == -1) {
Updated accordingly

2022-10-25 17:41 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        uint256 gbc = maximumQuarterlyDistribution();
I had left it as public to ensure that the UI can be sure to produce the same calculations as the contracts

2022-10-25 17:42 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        QuarterlyDistribution memory currentDistribution = distributions[getDistributionId()];
Updated to access `distributionId` via `proposal.distributionId`

2022-10-25 17:51 UTC, grandizzy commented on src/GrowthFund.sol
> +        if (block.number <= currentDistribution.endBlock || block.number > currentDistribution.endBlock + 50400) {
👍

2022-10-25 17:51 UTC, MikeHathaway commented on src/GrowthFund.sol
> +            return _screeningVote(currentTopTenProposals, account_, proposal, votes);
Updated

2022-10-25 17:54 UTC, grandizzy commented on src/GrowthFund.sol
> +        require(topTenProposals[getDistributionId()].length <= 10 && topTenProposals[getDistributionId()].length > 0, "CV:LIST_MALFORMED");
yep, sounds good if we can remove it or at least load length only once from storage. Maybe use custom error too

2022-10-25 17:56 UTC, MikeHathaway commented on src/GrowthFund.sol
> +    function _fundingVote(Proposal storage proposal_, address account_, QuadraticVoter storage voter_, int256 budgetAllocation_) internal returns (uint256) {
I agree that this would be a better approach for the `emit` but I had left in the extra parameters to ensure that we stayed compliant with third-party governance interfaces like tally.xyz: https://docs.tally.xyz/user-guides/tally-contract-compatibility/openzeppelin-governor

Updated to use `budgetAllocation_` in favor of local `allocationUsed` variable.

2022-10-25 18:27 UTC, MikeHathaway commented on src/GrowthFund.sol
> +            int256 budgetAllocation = abi.decode(params_, (int256));
The return statement is required to maintain compatibility with `super._castVote()` interface. It's more gas efficient to use the return value from `_fundingVote`

2022-10-25 18:30 UTC, grandizzy commented on src/GrowthFund.sol
> +            int256 budgetAllocation = abi.decode(params_, (int256));
👍

2022-10-25 18:30 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        require(topTenProposals[getDistributionId()].length <= 10 && topTenProposals[getDistributionId()].length > 0, "CV:LIST_MALFORMED");
Removed it entirely

2022-10-25 18:31 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        require(topTenProposals[getDistributionId()].length <= 10 && topTenProposals[getDistributionId()].length > 0, "CV:LIST_MALFORMED");
Removed entirely.

2022-10-25 18:37 UTC, MikeHathaway commented on src/GrowthFund.sol
> +                return uint256(voter.budgetRemaining);
It should only be able to go to 0, but converting it to uint256 results in additional casts in `fundingVote` and `castVote` to track votes allocated resulting in an actual increase in type casting

2022-10-25 18:59 UTC, MikeHathaway commented on src/GrowthFund.sol
> +                _updateFundedSlate(fundedProposals_, currentDistribution, newSlateHash);
Updated accordingly and removed `updateFundedSlate` function

2022-10-25 19:25 UTC, MikeHathaway commented on src/GrowthFund.sol
> +                voter.votingWeight = Maths.wpow(super._getVotes(account_, getScreeningPeriodEndBlock(currentDistribution) - 33, ""), 2);
Updated

2022-10-25 19:25 UTC, MikeHathaway commented on src/GrowthFund.sol
> +                return Maths.wpow(super._getVotes(account_, getScreeningPeriodEndBlock(currentDistribution) - 33, ""), 2);
Updated

2022-10-25 19:25 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        uint256 screeningPeriodEndBlock = getScreeningPeriodEndBlock(currentDistribution);
Updated

2022-10-25 19:28 UTC, MikeHathaway commented on src/GrowthFund.sol
> +                return uint256(voter.budgetRemaining);
Resolving this comment temporarily as it's causing my github page to glitch.

2022-10-25 19:36 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        bytes32 newSlateHash = getSlateHash(fundedProposals_);
Updated

2022-10-25 19:42 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        uint256 proposalId = hashProposal(targets, values, calldatas, keccak256(bytes(description)));
Updated

2022-10-25 19:42 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        uint256 proposalId = hashProposal(targets, values, calldatas, descriptionHash);
Updated

2022-10-25 20:55 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        extraordinaryFundingBaseQuorum = 50; // initialize base quorum percentrage required for extraordinary funding to 50%
the `extraordinaryFundingBaseQuorum` might change in the future as EFM proposals pass but this could also be calculated in alternative ways - not clear yet how that will be implemented given EFM is a WIP.

Simplified to only use a single token address like recommended. Left it as mutable while development is ongoing in case we wanted to deploy to a testnet, for example. Working on an approach using `vm.etch` to hardcode it during testing, but running into issues.

2022-10-26 13:05 UTC, grandizzy commented on src/GrowthFund.sol
> +contract GrowthFund is IGrowthFund, Governor, GovernorVotesQuorumFraction, ReentrancyGuard {
I think we can remove `is Governor here` because `GovernorVotesQuorumFraction` is `GovernorVotes` which is `Governor`. Then `function _getVotes(address account_, uint256 blockNumber_, bytes memory stage_) internal view override(GovernorVotes)` and `function quorum(uint256 blockNumber) public view override(GovernorVotesQuorumFraction) returns (uint256) {`
Happy to leave it as it is if you think makes thing clearer

2022-10-26 14:12 UTC, MikeHathaway commented on src/GrowthFund.sol
> +contract GrowthFund is IGrowthFund, Governor, GovernorVotesQuorumFraction, ReentrancyGuard {
Think it would be better to leave the Governor inheritance in to be explicit about how this is working. That being said, might be able to remove the QuorumFraction inheritance with the upcoming EFM pr

2022-10-26 14:14 UTC, grandizzy commented on src/GrowthFund.sol
> +contract GrowthFund is IGrowthFund, Governor, GovernorVotesQuorumFraction, ReentrancyGuard {
yeah makes sense, closing this comment

2022-10-27 06:05 UTC, grandizzy requested changes

2022-10-27 06:05 UTC, grandizzy commented on src/GrowthFund.sol
> +        proposalId_ = uint256(keccak256(abi.encode(targets_, values_, calldatas_, keccak256(bytes(description_)))));
I think would be better to do first `proposalId_ = super.propose(targets_, values_, calldatas_, description_);` and then do our custom code. This will execute `Governor` logic first and avoid double computation of `proposalId_` + extra return line. At the same time, `Governor.propose` checks for targets, values and calldata lengths to be the same, so our `checkProposal` modifier can be changed to only check
```
if (targets_.length != 1) revert InvalidProposal();
```
instead
```
if (targets_.length != 1 || values_.length != 1 || calldatas_.length != 1) {
            revert InvalidProposal();
}
```

2022-10-27 06:05 UTC, grandizzy commented on src/GrowthFund.sol
> +        if (values_[0] != 0) revert InvalidValues();
why should `values_[0]` be 0?
ah, is that because values is the amount of ETH to include and we're funding not with ETH but with Ajna tokens?

2022-10-27 06:05 UTC, grandizzy commented on src/GrowthFund.sol
> +        newProposal.proposalId = proposalId_;
Do we really need the `proposalId` to be recorded in `Proposal` struct? I see common pattern is to be computed based on `targets`, `values`, `calldatas` and `description` values or proposal Id passed in function as arguments, e.g.

in `_castVote` function we already have the param `uint256 proposalId_` which we can pass to `_screeningVote` and `_fundingVote` instead `Proposal storage proposal` and then passed further to `_findProposalIndex` function. Then proposal struct can be loaded from storage inside these functions instead at the very beginning of `_castVote` e.g. instead lines 357 and 358

```
        Proposal storage proposal = proposals[proposalId_];
        QuarterlyDistribution memory currentDistribution = distributions[proposal.distributionId];
```

we can only do 
```
QuarterlyDistribution memory currentDistribution = distributions[proposals[proposalId_].distributionId];
```

The `checkSlate` function can receive an array of funded proposal ids instead of `Proposal[]` (we should also add this to `IGrowthFund` interface as it is currently missing) and `getFundedProposalSlate` can retrieved list of funded proposal ids instead `Proposal[]` array (this one is also missing from `IGrowthFund` interface)

2022-10-27 06:11 UTC, grandizzy requested changes

2022-10-27 06:11 UTC, grandizzy commented on src/GrowthFund.sol
> +        uint8  support = 1;
since `budgetAllocation_` is of type `int256` and `voter_.budgetRemaining` the same, I suggest we rewrite following block (406 to 419) as
```
        uint8  support = budgetAllocation_ < 0 ? 0 : 1;
        voter_.budgetRemaining += budgetAllocation_;
```
I suggest `budgetAllocated` to be named var `budgetAllocated_` in `_fundingVote` function signature and get rid of `return budgetAllocated;`

2022-10-27 06:33 UTC, grandizzy requested changes

2022-10-27 06:33 UTC, grandizzy commented on src/GrowthFund.sol
> +        topTenProposals[proposal_.distributionId][uint256(_findProposalIndex(proposal_.proposalId, topTenProposals[proposal_.distributionId]))].qvBudgetAllocated = proposal_.qvBudgetAllocated;
avoid loading `topTenProposals[proposal_.distributionId]` from storage twice here, we can load it once and then do something like `topTenProposals[uint256(_findProposalIndex(proposal_.proposalId, topTenProposals)].qvBudgetAllocated` which is more readable too. or have a different var `proposalIndex = uint256(_findProposalIndex(proposal_.proposalId, topTenProposals)` and then `topTenProposals[proposalIndex].qvBudgetAllocated = proposal_.qvBudgetAllocated`

2022-10-27 11:58 UTC, grandizzy commented on src/GrowthFund.sol
> +        return true;
I think we should add a comment here why always return true and point to the `_voteSucceeded` as the only way we use to mark a proposal as `Succeeded` (similar with natspec for `votingDelay` where we have `Since no voting delay is implemented, this is hardcoded to 0`)

2022-10-27 17:59 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        if (values_[0] != 0) revert InvalidValues();
Yes exactly, that would be for an ETH transfer, and the `values` field is part of the standard interface so I left it and forced it to be 0.

2022-10-27 18:05 UTC, grandizzy commented on src/GrowthFund.sol
> +        if (values_[0] != 0) revert InvalidValues();
👍

2022-10-27 18:29 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        return true;
Updated accordingly

2022-10-27 19:45 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        newProposal.proposalId = proposalId_;
If we removed `proposalId` from the `Proposal` struct than I don't think we would be able to execute the `_findProposalIndex` function? 

Also, using proposalIds instead of working with a calldata array would be much more expensive given the relative costs of working with calldata vs storage.

2022-10-27 19:50 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        uint8  support = 1;
This won't work since voting affirmatively for a proposal would result in an increasing budget remaining. Can add a ternary for the `voter_.budgetRemaining` modification as well, but that results in a net increase in computation compared to the existing approach.

I don't see where there's a `budgetAllocated` param in the function signature? 

Also, what is the purpose of removing the return statement? A return statement is required in `_castVote` to comply with the interface, and duplicating the logic required to return budget allocation in uint terms results in increased gas as compared to just returning `_fundingVote`

2022-10-27 20:21 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        topTenProposals[proposal_.distributionId][uint256(_findProposalIndex(proposal_.proposalId, topTenProposals[proposal_.distributionId]))].qvBudgetAllocated = proposal_.qvBudgetAllocated;
Updated accordingly, definitely much more readable.

2022-10-27 20:34 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        proposalId_ = uint256(keccak256(abi.encode(targets_, values_, calldatas_, keccak256(bytes(description_)))));
Good call, updated to use `proposalId = super.propose()`, as well as above modifier.

2022-10-27 20:34 UTC, MikeHathaway commented on src/interfaces/IGrowthFund.sol
> +interface IGrowthFund {
Renamed accordingly.

2022-10-28 15:12 UTC, grandizzy commented on src/GrowthFund.sol
> +        newProposal.proposalId = proposalId_;
makes sense, I missed this

2022-10-28 15:22 UTC, grandizzy commented on src/GrowthFund.sol
> +        uint8  support = 1;
> This won't work since voting affirmatively for a proposal would result in an increasing budget remaining. Can add a ternary for the `voter_.budgetRemaining` modification as well, but that results in a net increase in computation compared to the existing approach.
> 
> I don't see where there's a `budgetAllocated` param in the function signature?

Sorry, not `budgetAllocated` but `budgetAllocation_` I mean this one https://github.com/ajna-finance/GrowthCoordinationFund/blob/growth-fund-proto/src/GrantFund.sol#L391 which then we check if lower than 0 and add to `budgetRemaining`: `voter_.budgetRemaining += budgetAllocation_` else subtract from `budgetRemaining`
Doesn't seem right to me since it's an `int256` type we can just use it's sign and avoid checking if negative... Was wrong in initial comment  I think it should be `voter_.budgetRemaining -= budgetAllocation_` instead `+=`
> 
> Also, what is the purpose of removing the return statement? A return statement is required in `_castVote` to comply with the interface, and duplicating the logic required to return budget allocation in uint terms results in increased gas as compared to just returning `_fundingVote`

My suggestion is to use named returned variable (not get rid of return entirely) as afaik is better o  gas costs, that instead declaring it here https://github.com/ajna-finance/GrowthCoordinationFund/blob/growth-fund-proto/src/GrantFund.sol#L420 and returning it here https://github.com/ajna-finance/GrowthCoordinationFund/blob/growth-fund-proto/src/GrantFund.sol#L422 you could just have `_fundingVote returns (uint256 budgetAllocated_)` and set value of `budgetAllocated_` at line 420

2022-10-28 16:27 UTC, MikeHathaway commented on src/GrowthFund.sol
> +        uint8  support = 1;
Ah I see, I misunderstood the return variable point. Updated to use named return variable. 

Might be missing something, but flipping the sign still doesn't work for budgetRemaining, it just results in a vote against increasing their voting budget.

2022-10-28 16:35 UTC, grandizzy approved these changes
all good, let's merge it and we can follow up on other points in separate PRs

2022-10-28 16:45 UTC, merged