Extraordinary Funding Mechanism
ajna-finance/ecosystem-coordination pull request #22
Opened 2022-11-01 05:09 UTC by MikeHathaway

- Implement Extraordinary Funding Mechanism
- Override OpenZeppelin.Governor.propose and OZ.Governor.state()
- Use our own Proposal structs to handle proposal state lifecycle
- Split each mechanism into separate abstract contracts that `GrantFund.sol` inherits from

2022-11-07 22:34 UTC, EdNoepel reviewed
Haven't reviewed the tests yet, but contracts look good upon first review.

2022-11-07 22:34 UTC, EdNoepel commented on src/GrantFund.sol
> +            else if (distribution.endBlock >= block.number && !voteSucceeded) return IGovernor.ProposalState.Active;
Why do we need to check `voteSucceded` here?

2022-11-07 22:34 UTC, EdNoepel commented on src/base/ExtraordinaryFunding.sol
> +        proposalId_ = hashProposal(targets_, values_, calldatas_, descriptionHash_);
Should the proposal hash include the funding mechanism?

2022-11-07 22:34 UTC, EdNoepel commented on src/base/ExtraordinaryFunding.sol
> +
Suggestion: Would be more readable to call a `_validateCallData` routine inside the loop.

2022-11-07 22:34 UTC, EdNoepel commented on src/base/ExtraordinaryFunding.sol
> +            uint256 tokensRequested;
Amount in the treasury can change between `proposeExtraordinary` and execution.  I agree `tokensRequested` is a better implementation, but it differs from requirements in section 9.2.2.4 of the whitepaper.

2022-11-07 22:34 UTC, EdNoepel commented on src/base/ExtraordinaryFunding.sol
> +        }
nit: expecting bat-else `} else {`

2022-11-07 22:34 UTC, EdNoepel commented on src/base/ExtraordinaryFunding.sol
> +        emit VoteCast(account_, proposalId_, 1, votes_, "");
Note to reviewers: args found here: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/governance/IGovernor.sol#L55

2022-11-07 22:34 UTC, EdNoepel commented on src/base/ExtraordinaryFunding.sol
> +        if (proposal.votesReceived >= proposal.tokensRequested + getPercentageOfTreasury(getMinimumThresholdPercentage())) {
Let's say there's 1,000,000 tokens in treasury and it's the second vote.  Proposer requests 200,000 tokens (20%).  This means 50+20+5=75%, or 750,000 tokens should be required.

This logic would take 200,000 + (0.55 * 1,000,000) = 750,000.  So yeah, looks good.

2022-11-07 22:34 UTC, EdNoepel commented on src/base/ExtraordinaryFunding.sol
> +    function getPercentageOfTreasury(uint256 percentage_) public view returns (uint256) {
Method name is confusing, because it suggests the function will return a percentage.  But the natspec explains it nicely.

2022-11-07 22:50 UTC, MikeHathaway commented on src/base/ExtraordinaryFunding.sol
> +    function getPercentageOfTreasury(uint256 percentage_) public view returns (uint256) {
Agreed it could be better - what do you think about `getPercentageOfTreasuryTokenEquivalent`? More specific albeit Java-esque

2022-11-07 22:50 UTC, MikeHathaway commented on src/base/ExtraordinaryFunding.sol
> +        }
Updated

2022-11-07 23:36 UTC, MikeHathaway commented on src/base/ExtraordinaryFunding.sol
> +
Updated accordingly - the gas cost of using a common routine was extremely minimal

2022-11-07 23:58 UTC, MikeHathaway commented on src/GrantFund.sol
> +            else if (distribution.endBlock >= block.number && !voteSucceeded) return IGovernor.ProposalState.Active;
We don't - I had added when maintaining parity between standard and extraordinary flows in `state()`. It's only needed in the Extraordinary mechanism, so I will remove it.

2022-11-08 00:03 UTC, MikeHathaway commented on src/base/ExtraordinaryFunding.sol
> +            uint256 tokensRequested;
This is a good call out. I will discuss it with business tomorrow with the purpose of updating the whitepaper to match this. I don't think it's possible to retroactively update the `tokensRequested` param in the calldata without altering the resulting `proposalId` hash, and it's likely easier to reason about a specified amount of tokens from a social layer perspective.

2022-11-08 01:37 UTC, EdNoepel commented on src/base/ExtraordinaryFunding.sol
> +    function getPercentageOfTreasury(uint256 percentage_) public view returns (uint256) {
`getSliceOfTreasury`?  I feel like "percentage" shouldn't be in the name if it doesn't return a percentage.

2022-11-08 01:54 UTC, MikeHathaway commented on src/base/ExtraordinaryFunding.sol
> +    function getPercentageOfTreasury(uint256 percentage_) public view returns (uint256) {
Sounds good, updated accordingly

2022-11-08 02:46 UTC, MikeHathaway commented on src/base/ExtraordinaryFunding.sol
> +        proposalId_ = hashProposal(targets_, values_, calldatas_, descriptionHash_);
We could add a fifth parameter to it, but the `proposalId` generation process would then have to be different between Standard, and Extraordinary since Standard still utilizes the `Governor.execute()` method. That being said, they're both just hashes so shouldn't otherwise interfere. I had been thinking that we might want to create a requirement spec for the `description_` string, but it might be cleaner to just add the fifth parameter as `bytes("extraordinary")` and avoid any collisions that way.

2022-11-08 03:54 UTC, EdNoepel commented on src/base/ExtraordinaryFunding.sol
> +        proposalId_ = hashProposal(targets_, values_, calldatas_, descriptionHash_);
I'm happy using `description_` string to avoid collisions.

2022-11-10 16:18 UTC, MikeHathaway commented on src/base/ExtraordinaryFunding.sol
> +            uint256 tokensRequested;
The whitepaper has been updated to match the logic of the `tokensRequested` calldata based implementation.

2022-11-10 17:45 UTC, EdNoepel approved these changes
LGTM

2022-11-13 18:51 UTC, grandizzy requested changes

2022-11-13 18:51 UTC, grandizzy commented on src/GrantFund.sol
> +        if (standardFundingProposals[proposalId_].proposalId != 0) return 0; // 0 = standard funding proposal
recommend using enums for better clarity, e.g. `enum FundingProposalMechanism{ STANDARD, EXTRAORDINARY }`

2022-11-13 18:51 UTC, grandizzy commented on src/GrantFund.sol
> +            else if (distribution.endBlock >= block.number) return IGovernor.ProposalState.Active;
in extraordinary check we do `else if (proposal.endBlock >= block.number && !voteSucceeded) return IGovernor.ProposalState.Active;` shouldn't `voteSucceeded` be checked here as well?

2022-11-13 18:51 UTC, grandizzy commented on src/GrantFund.sol
> +            if (proposal.executed) return IGovernor.ProposalState.Executed;
I think we can externalize this in a  `_getProposalState` function and reuse code, that is instead having 2 blocks of code to determine proposal state we could have only one. also not loading entire structs in memory could save some gas, so `state` function can look something like

```

    function state(uint256 proposalId_) public view override(Governor) returns (IGovernor.ProposalState) {
        uint8 mechanism = findMechanismOfProposal(proposalId_);

        // standard proposal state checks
        if (mechanism == FundingProposalMechanism.STANDARD) {
            return _getProposalState(
                standardFundingProposals[proposalId_].executed,
                distributions[_distributionIdCheckpoints.latest()].endBlock,
                _standardFundingVoteSucceeded(proposalId_)
            );
        }
        // extraordinary funding proposal state checks
        else if (mechanism == FundingProposalMechanism.EXTRAORDINARY) {
            return _getProposalState(
                extraordinaryFundingProposals[proposalId_].executed,
                extraordinaryFundingProposals[proposalId_].endBlock,
                _extraordinaryFundingVoteSucceeded(proposalId_)
            );
        }
    }

    function _getProposalState(bool executed, uint256 endBlock, bool voteSucceeded) internal view returns (IGovernor.ProposalState) {
        if (executed) return IGovernor.ProposalState.Executed;
        else if (endBlock >= block.number && !voteSucceeded) return IGovernor.ProposalState.Active;
        else if (voteSucceeded) return IGovernor.ProposalState.Succeeded;
        else return IGovernor.ProposalState.Defeated;
    }
```

2022-11-13 18:51 UTC, grandizzy commented on src/GrantFund.sol
>          }
should we revert or return a `IGovernor.ProposalState.Defeated` if `mechanism` is not `STANDARD` nor `EXTRAORDINARY`?

2022-11-13 18:51 UTC, grandizzy commented on src/base/StandardFunding.sol
> +    mapping(uint256 => Proposal[]) topTenProposals;
if I correctly get this, we're going to keep all proposals in `standardFundingProposals` mapping: `mapping(uint256 => Proposal) standardFundingProposals;` (when executed we're not removing from mapping)
Do we really need here a mapping to the entire Proposal struct 
`mapping(uint256 => Proposal[]) topTenProposals`
or can this be simplified to
`mapping(uint256 => uint256[]) topTenProposals`
where we don't keep entire struct again but rather the `proposalId`s?
Then whenever we change something to the proposal we're only going to maintain the struct in `standardFundingProposals` and not update in 2 places (even 3 if we consider the `fundedProposalSlates` mapping bellow too)

2022-11-13 18:51 UTC, grandizzy commented on src/base/StandardFunding.sol
> +    mapping(uint256 => mapping(bytes32 => Proposal[])) fundedProposalSlates;
same as above, cannot this be simplified to `mapping(uint256 => mapping(bytes32 => uint256[])) fundedProposalSlates;` that is `distributionId => slate hash => proposalId[]` ?

2022-11-13 18:51 UTC, grandizzy commented on src/base/ExtraordinaryFunding.sol
> +    ExtraordinaryFundingProposal[] public fundedExtraordinaryProposals;
same comment as for the standard funding impl, cannot we just point here to `proposalId` rather than entire struct, so to have ` uint256[] public fundedExtraordinaryProposalsIds;` list of arrays and for other details to use struct within `mapping (uint256 => ExtraordinaryFundingProposal) public extraordinaryFundingProposals;` ?

2022-11-14 00:31 UTC, MikeHathaway commented on src/GrantFund.sol
> +        if (standardFundingProposals[proposalId_].proposalId != 0) return 0; // 0 = standard funding proposal
Updated

2022-11-14 00:33 UTC, MikeHathaway commented on src/GrantFund.sol
>          }
I don't think `Defeated` should be used since the proposal should never become active or be open for consideration without passing the mechanism check, so any proposal that doesn't return a value is inherently an invalid argument.

2022-11-14 00:52 UTC, MikeHathaway commented on src/GrantFund.sol
> +            else if (distribution.endBlock >= block.number) return IGovernor.ProposalState.Active;
It's needed only in the extraordinary funding mechanism because proposals can be executed immediately upon passing the required threshold, whereas in the standard flow, proposals can't be executed until the 1 week challenge period of providing off-chain calculated funding slates has completed. Until that week has passed, a proposal will be active but any success is inherently temporary and may change in the event of the provision of a superior slate, so active is likely less misleading.

2022-11-14 01:05 UTC, MikeHathaway commented on src/GrantFund.sol
> +            if (proposal.executed) return IGovernor.ProposalState.Executed;
As explained above `voteSucceeded` is only a necessary check in the extraordinary flow, so the two sections logic would diverge. Avoiding loading the entire struct is a good call out, updated accordingly for significant gas savings.

2022-11-14 01:25 UTC, MikeHathaway commented on src/base/ExtraordinaryFunding.sol
> +    ExtraordinaryFundingProposal[] public fundedExtraordinaryProposals;
Updated accordingly

2022-11-14 04:26 UTC, MikeHathaway commented on src/base/StandardFunding.sol
> +    mapping(uint256 => Proposal[]) topTenProposals;
Good call out, updated accordingly for huge gas savings.

2022-11-14 04:26 UTC, MikeHathaway commented on src/base/StandardFunding.sol
> +    mapping(uint256 => mapping(bytes32 => Proposal[])) fundedProposalSlates;
Updated accordingly

2022-11-14 06:25 UTC, grandizzy requested changes
Looks good! only some more couple of comments / suggestions

2022-11-14 06:25 UTC, grandizzy commented on src/GrantFund.sol
> +                ExtraordinaryFundingProposal memory proposal = extraordinaryFundingProposals[proposalId];
I think we could save gas here too by not loading entire struct in memory (as we only need the `proposalId` and `startBlock`), just by
```
                // one token one vote for extraordinary funding
                if (extraordinaryFundingProposals[proposalId].proposalId != 0) {
                    uint256 proposalStartBlock = extraordinaryFundingProposals[proposalId].startBlock;
                    return _getVotesSinceSnapshot(account_, proposalStartBlock - 33, proposalStartBlock);
                }
```

2022-11-14 06:25 UTC, grandizzy commented on src/base/ExtraordinaryFunding.sol
> +            return 0.500000000000000000 * 1e18;
probably not making a difference in terms of gas (as afaik Solidity will add this inline) but maybe we should make `0.500000000000000000 * 1e18` as a meaningful constant?

2022-11-14 06:25 UTC, grandizzy commented on src/base/ExtraordinaryFunding.sol
> +            return 0.500000000000000000 * 1e18 + (fundedExtraordinaryProposals.length * (0.050000000000000000 * 1e18));
should the second one be `0.05 * 1e18` or still `0.5 * 1e18`?

2022-11-14 06:25 UTC, grandizzy commented on src/base/ExtraordinaryFunding.sol
> +        newProposal.proposalId = proposalId_;
NIT: would be nice to align these on `=` for better readability

2022-11-14 06:25 UTC, grandizzy commented on src/base/StandardFunding.sol
> +        newDistributionPeriod.id = newDistributionId_;
NIT: align these to `=` sign

2022-11-14 06:25 UTC, grandizzy commented on src/base/StandardFunding.sol
> +        QuarterlyDistribution memory lastDistribution = distributions[_distributionIdCheckpoints.latest()];
we could save some gas by not loading entire struct in memory and checking
```
if (block.number <= distributions[_distributionIdCheckpoints.latest()].endBlock) revert DistributionPeriodStillActive();
```
at line 123

2022-11-14 06:25 UTC, grandizzy commented on src/base/StandardFunding.sol
> +        uint256 GrantFundBalance = IERC20(ajnaTokenAddress).balanceOf(address(this));
NIT: should be `uint256 grantFundBalance` with lowercase G

2022-11-14 06:25 UTC, grandizzy commented on src/base/StandardFunding.sol
> +        newProposal.proposalId = proposalId_;
NIT: align these to `=` sign

2022-11-14 06:25 UTC, grandizzy commented on src/base/StandardFunding.sol
> +    mapping(uint256 => QuarterlyDistribution) distributions;
I suggest specifying visibility of variables instead using the default

2022-11-14 06:51 UTC, MikeHathaway commented on src/GrantFund.sol
> +                ExtraordinaryFundingProposal memory proposal = extraordinaryFundingProposals[proposalId];
Updated accordingly

2022-11-14 06:52 UTC, MikeHathaway commented on src/base/ExtraordinaryFunding.sol
> +            return 0.500000000000000000 * 1e18 + (fundedExtraordinaryProposals.length * (0.050000000000000000 * 1e18));
It should be `0.05` as the threshold increases by 5% with each successful proposal

2022-11-14 06:53 UTC, MikeHathaway commented on src/base/ExtraordinaryFunding.sol
> +        newProposal.proposalId = proposalId_;
Aligned

2022-11-14 06:53 UTC, MikeHathaway commented on src/base/StandardFunding.sol
> +        newDistributionPeriod.id = newDistributionId_;
Aligned

2022-11-14 06:54 UTC, MikeHathaway commented on src/base/StandardFunding.sol
> +        uint256 GrantFundBalance = IERC20(ajnaTokenAddress).balanceOf(address(this));
Removed the variable entirely

2022-11-14 06:55 UTC, MikeHathaway commented on src/base/StandardFunding.sol
> +        newProposal.proposalId = proposalId_;
Aligned

2022-11-14 06:57 UTC, MikeHathaway commented on src/base/StandardFunding.sol
> +        QuarterlyDistribution memory lastDistribution = distributions[_distributionIdCheckpoints.latest()];
Updated accordingly

2022-11-14 14:50 UTC, grandizzy approved these changes
LGTM! Was also thinking at some other improvement (that we can follow up on subsequent PR) - since there's a `quarterly distribution` do we really need to keep distribution ids as uint256 data type or something like uint128 or uint64 should suffice?

2022-11-14 17:26 UTC, MikeHathaway commented on src/base/StandardFunding.sol
> +    mapping(uint256 => QuarterlyDistribution) distributions;
Are you suggesting a change to the visibility here, or just make it explicit? The default would be `internal`, which I believe is the correct visibility since it's inherited, and getters are provided for external consumption

2022-11-14 17:37 UTC, grandizzy commented on src/base/StandardFunding.sol
> +    mapping(uint256 => QuarterlyDistribution) distributions;
Ah, no change, only make it explicit

2022-11-14 17:42 UTC, MikeHathaway commented on src/base/ExtraordinaryFunding.sol
> +            return 0.500000000000000000 * 1e18;
Would normally agree with moving it out, but in this case that value is only used in that one function, and the threshold it's tied to also changes over time so thought it might be confusing to extract.

2022-11-14 17:48 UTC, MikeHathaway commented on src/base/StandardFunding.sol
> +    mapping(uint256 => QuarterlyDistribution) distributions;
Updated accordingly

2022-11-14 17:49 UTC, MikeHathaway commented
> LGTM! Was also thinking at some other improvement (that we can follow up on subsequent PR) - since there's a `quarterly distribution` do we really need to keep distribution ids as uint256 data type or something like uint128 or uint64 should suffice?

So the `Checkpoints.History` utility natively operates upon `uint224`, reducing the bits might require casting

2022-11-14 19:02 UTC, merged