Invariants Testing
ajna-finance/ecosystem-coordination pull request #51
Opened 2023-03-09 21:55 UTC by MikeHathaway

Add tests for the majority of the standard funding mechanism's invariants. 
- Created scenarios for each portion of the distribution period end to end, with tests for each period.
- Update test/ directory structure

There are a lot of outstanding todos which I'm looking to fix over the next few days, ideally in a separate PR. Currently being worked:
- Global GrantFund invariants
- More sophisticated time manipulation

A list of the completion status of the Standard invariants is available here: https://www.notion.so/worlds-best-crypto-lending-platform/GrantFund-Standard-Funding-Mechanism-invariant-testing-8b87a0a814a5405aa42f931590d7a332?pvs=4

2023-04-03 00:42 UTC, ith-harvey reviewed
Would like to see the invariants in README rewritten using the actual variable names in the contracts to more closely match the `contracts` repo invariants as well as provide more clarity to auditors / code reviewers. Happy to help with that.

Alot of comments throughout the code... seeing as there is some future work and this is a WIP I think FIXME's are fine but random one off comments without any context are confusing, I suggest removing those if and where possible. Didn't flag all of them as there were too many.

Structure looks decent, once some of the structural inquiries are addressed (either a response or change) happy to approve so we can get this scaffolding in.

2023-04-03 00:42 UTC, ith-harvey commented on foundry.toml
> +fail_on_revert = true  # Fail the test if the contract reverts
I'm personally a fan of fail on revert = true as that was the original instruction provided by Lucas.

However, in the event where we are not making enough progress due to our timeline it may make sense to set this to false and run using the number of runs vs reverts as a goalpost just like we are doing in contracts repo

2023-04-03 00:42 UTC, ith-harvey commented on test/invariants/INVARIANTS.md
> +   - **GF2**: Treasury should always be less than or equal to the contract's token blance.
Unclear on what this invariant is saying... is Treasury in this context a variable? If so we should use `treasury` so it's a bit clearer?

2023-04-03 00:42 UTC, ith-harvey commented on test/invariants/base/StandardTestBase.sol
> +        // vm.rollFork(block.number + 100);
is this comment needed? suggest removing

2023-04-03 00:42 UTC, ith-harvey commented on test/invariants/base/TestBase.sol
> +        _token = IAjnaToken(0x9a96ec9B57Fb64FbC60B423d1f4da7691Bd35079);
suggest renaming to `_ajna` to match contract repo

2023-04-03 00:42 UTC, ith-harvey commented on test/invariants/handlers/Handler.sol
> +    IAjnaToken        internal  _token;
suggest renaming `_token` -> `_ajna`

2023-04-03 00:42 UTC, ith-harvey commented on test/invariants/handlers/Handler.sol
> +    constructor(address payable grantFund_, address token_, address tokenDeployer_, uint256 numOfActors_, uint256 tokensToDistribute_) {
suggest new line after every arg to clean up formatting

2023-04-03 00:42 UTC, ith-harvey commented on test/invariants/handlers/Handler.sol
> +        actors = _buildActors(numOfActors_, tokensToDistribute_);
Due to the size the contracts repo, the one off excpetions in certain scenarios and the short timelines we decided to go against supplying tokens to actors on every call and went with supplying them the tokens at in the setup.

I don't much like that approach and would suggest we provide tokens to the actor performing the call when the action is called. I think this results in less errors and more depth of calls. More difficult at first but easier in the later stages of dev

Please see how maple does it -> https://github.com/maple-labs/maple-core-v2/blob/main/tests/invariants/actors/LpHandler.sol#L79

2023-04-03 00:42 UTC, ith-harvey commented on test/invariants/handlers/StandardHandler.sol
> +        // vm.roll(block.number + 100);
is this comment still needed?

2023-04-03 00:42 UTC, ith-harvey commented on test/invariants/handlers/StandardHandler.sol
> +            // FIXME: remove this
not sure why this exists / what issue this FixMe handles

2023-04-03 00:42 UTC, ith-harvey commented on test/invariants/handlers/StandardHandler.sol
> +        console.log("description", description);
log still needed? recommend removing

2023-04-03 00:42 UTC, ith-harvey commented on test/invariants/StandardFinalizeInvariant.t.sol
> +    function invariant_CS1_CS2_CS3_CS4_CS5() external {
I like the idea of breaking each invariant into their own separate test even if the function remains a one liner... much like how Maple does it and I suggest we do it here too. Think it results in cleaner code with less comments, easier to follow IMO -> https://github.com/maple-labs/maple-core-v2/blob/00f01ae7175885f8d49ac201a1c72465e320b2f6/tests/invariants/DefaultsInvariants.t.sol#L66

2023-04-03 03:04 UTC, MikeHathaway commented on test/invariants/handlers/Handler.sol
> +        actors = _buildActors(numOfActors_, tokensToDistribute_);
That isn't possible here as actors need the tokens delegated by certain blocks to be able to take actions. Vote counts would be 0

2023-04-03 10:44 UTC, grandizzy requested changes
looks good for the first iteration (noticed several TODOs), had couple of comments / suggestions.

2023-04-03 10:44 UTC, grandizzy commented on test/invariants/StandardFinalizeInvariant.t.sol
> +            assertTrue(fundingVotesReceived >= 0);
for invariants we may want to use `require` with specific revert reason, like `require(fundingVotesReceived >= 0, "CS3: proposal slate contains proposal with negative funding")` or something along these lines

2023-04-03 10:44 UTC, grandizzy commented on test/invariants/INVARIANTS.md
> +   - **GF1**: Unused proposal states should always be 0.
I don't find where these 2 invariants are checked in code, can you clarify?

2023-04-03 10:44 UTC, grandizzy commented on test/invariants/INVARIANTS.md
> +- #### Distribution Period:
same as above, I cannot find in code where these invariants are checked

2023-04-03 10:44 UTC, grandizzy commented on test/invariants/StandardScreeningInvariant.t.sol
> +        // invariant: 10 or less proposals should make it through the screening stage
would be nice to mark it as `SS1`

2023-04-03 10:44 UTC, grandizzy commented on test/invariants/StandardScreeningInvariant.t.sol
> +        if (_standardHandler.screeningVotesCast() > 0) {
if I am not wrong this one is `SS2`, we should mark it as such

2023-04-03 10:44 UTC, grandizzy commented on test/invariants/StandardScreeningInvariant.t.sol
> +            assertTrue(votesReceived <= 1_000_000_000 * 1e18);
token supply can be less than 1bn in case reserve auction taken. I suggest to replace this with `token.totalSupply()` call and maybe add a fuzz call for burning ajna tokens

2023-04-03 10:44 UTC, grandizzy commented on test/invariants/StandardFundingInvariant.t.sol
> +        // invariant: 10 or less proposals should make it through the screening stage
looks like `SS1`?

2023-04-03 10:44 UTC, grandizzy commented on test/invariants/StandardFundingInvariant.t.sol
> +        assertTrue(topTenProposals.length <= 10);
can use `assertLe` and `assertGe` like shown in https://book.getfoundry.sh/forge/invariant-testing#defining-invariants or the `require` with invariant specified in revert reason (I think 2nd approach is better / cleaner)

2023-04-03 10:44 UTC, grandizzy commented on test/invariants/StandardFundingInvariant.t.sol
> +            // TODO: check getFundingPowerVotes to see if remaining voting power matches expectations
why the TODO and next line commented?

2023-04-03 10:44 UTC, grandizzy commented on test/invariants/StandardScreeningInvariant.t.sol
> +            assertTrue(votesReceived >= 0);
should invariant be `votesReceived >= 0` or strictly greater than 0 `votesReceived > 0` ?

2023-04-03 10:44 UTC, grandizzy commented on test/invariants/base/TestBase.sol
> +        _token = IAjnaToken(0x9a96ec9B57Fb64FbC60B423d1f4da7691Bd35079);
for `contracts` repo we introduced a `burnableToken` and use that instead forking mainnet and Ajna. This makes tests faster and avoid being rate limited by infura, see https://github.com/ajna-finance/contracts/blob/develop/tests/forge/ERC20Pool/invariants/base/BaseHandler.sol#L84

2023-04-03 10:44 UTC, grandizzy commented on test/invariants/handlers/Handler.sol
> +    // modifier useBlock() {
can this modifier and `setCurrentBlock` function below be removed?

2023-04-03 10:44 UTC, grandizzy commented on test/invariants/handlers/StandardHandler.sol
> +    function claimDelegateReward(uint256 actorIndex_, uint256 proposalToExecute_) external useRandomActor(actorIndex_) {
`proposalToExecute_` is not used

2023-04-03 10:44 UTC, grandizzy commented on test/invariants/handlers/StandardHandler.sol
> +            (uint256 proposalId, uint24 distributionId, uint128 votesReceived, uint128 tokensRequested, int128 fundingVotesReceived, bool executed) = _grantFund.getProposalInfo(standardFundingProposa
we may want to log the `fundingVotesReceived` too (and get rid of compiler warning)?

2023-04-03 10:44 UTC, grandizzy commented on test/invariants/handlers/StandardHandler.sol
> +    function countNegativeFundingVotes(address actor_, IStandardFunding.FundingVoteParams[] memory fundingVotes_) public pure returns (uint256 count_) {
`actor_` is not used, I think we'd want to check votes used per actor here?

2023-04-03 10:44 UTC, grandizzy commented on test/invariants/StandardFinalizeInvariant.t.sol
> +        (, , , uint128 fundsAvailable, , bytes32 topSlateHash) = _grantFund.getDistributionPeriodInfo(distributionId);
`fundsAvailable` is not used, should we remove or assert invariant `CS1` here?

2023-04-03 10:44 UTC, grandizzy commented on test/invariants/StandardFinalizeInvariant.t.sol
> +        // assertTrue(totalRewardsClaimed <= fundsAvailable * 9 / 10);
which assert is the right one, the one above or this one that is commented out?

2023-04-03 10:44 UTC, grandizzy commented on test/invariants/StandardFinalizeInvariant.t.sol
> +            (uint128 votingPower, uint128 remainingVotingPower, uint256 numberOfProposalsVotedOn) = _grantFund.getVoterInfo(distributionId, actor);
`votingPower` is not used, I suspect we want to assert it? Same for `remainingVotingPower` and ``numberOfProposalsVotedOn``, should we check total voting power equals remaining voting power + numberOfProposalsVotedOn?

2023-04-03 10:44 UTC, grandizzy commented on test/invariants/StandardFinalizeInvariant.t.sol
> +        (, , , uint128 fundsAvailable, , bytes32 topSlateHash) = _grantFund.getDistributionPeriodInfo(distributionId_);
`fundsAvailable` is not used, do we want to log it?

2023-04-03 10:44 UTC, grandizzy commented on test/invariants/handlers/StandardHandler.sol
> +            require(
not sure if worth changing here but for `contracts` we have defined `_ensurePoolError` function with all known pool errors https://github.com/ajna-finance/contracts/blob/develop/tests/forge/ERC20Pool/invariants/base/BaseHandler.sol#L185 At minimum would be nice to have the `"Unexpected revert error"` reason

2023-04-03 17:59 UTC, MikeHathaway commented on test/invariants/StandardFinalizeInvariant.t.sol
> +            assertTrue(fundingVotesReceived >= 0);
Yeah I like that idea. I will update it accordingly

2023-04-03 18:01 UTC, MikeHathaway commented on test/invariants/INVARIANTS.md
> +   - **GF1**: Unused proposal states should always be 0.
They aren't checked yet. In order to properly test distribution period I need to first improve the way we manipulate time. The system only functions properly when it's at certain block heights, so need to be able to progress between the stages, as well as between different distribution periods.

2023-04-03 18:04 UTC, MikeHathaway commented on test/invariants/handlers/StandardHandler.sol
> +            require(
I agree about adding "Unexpected revert error". It's cleaner with `ensurePoolError`, but i'm concerned that some test granularity is lost without the checks for the specific reverts (i.e. only those should ever be seen, not a different pool error).

2023-04-03 18:12 UTC, grandizzy commented on test/invariants/handlers/StandardHandler.sol
> +            require(
I think that granularity is already covered by unit tests but I'm OK with either ways

2023-04-03 20:30 UTC, MikeHathaway commented on test/invariants/handlers/StandardHandler.sol
> +            // FIXME: remove this
removed

2023-04-03 20:30 UTC, MikeHathaway commented on test/invariants/handlers/StandardHandler.sol
> +        // vm.roll(block.number + 100);
removed

2023-04-03 20:31 UTC, MikeHathaway commented on test/invariants/handlers/StandardHandler.sol
> +        console.log("description", description);
removed

2023-04-03 20:31 UTC, MikeHathaway commented on test/invariants/handlers/Handler.sol
> +    constructor(address payable grantFund_, address token_, address tokenDeployer_, uint256 numOfActors_, uint256 tokensToDistribute_) {
updated

2023-04-03 20:32 UTC, MikeHathaway commented on test/invariants/base/StandardTestBase.sol
> +        // vm.rollFork(block.number + 100);
removed

2023-04-03 20:32 UTC, MikeHathaway commented on test/invariants/StandardFinalizeInvariant.t.sol
> +        (, , , uint128 fundsAvailable, , bytes32 topSlateHash) = _grantFund.getDistributionPeriodInfo(distributionId_);
added a log

2023-04-03 20:33 UTC, MikeHathaway commented on test/invariants/handlers/StandardHandler.sol
> +    function claimDelegateReward(uint256 actorIndex_, uint256 proposalToExecute_) external useRandomActor(actorIndex_) {
removed

2023-04-03 20:33 UTC, MikeHathaway commented on test/invariants/handlers/StandardHandler.sol
> +            (uint256 proposalId, uint24 distributionId, uint128 votesReceived, uint128 tokensRequested, int128 fundingVotesReceived, bool executed) = _grantFund.getProposalInfo(standardFundingProposa
logged

2023-04-03 20:34 UTC, MikeHathaway commented on test/invariants/handlers/StandardHandler.sol
> +    function countNegativeFundingVotes(address actor_, IStandardFunding.FundingVoteParams[] memory fundingVotes_) public pure returns (uint256 count_) {
removed

2023-04-03 20:34 UTC, MikeHathaway commented on test/invariants/StandardFinalizeInvariant.t.sol
> +        // assertTrue(totalRewardsClaimed <= fundsAvailable * 9 / 10);
Updated to check the totals across all claimers

2023-04-03 20:43 UTC, MikeHathaway commented on test/invariants/StandardFinalizeInvariant.t.sol
> +            (uint128 votingPower, uint128 remainingVotingPower, uint256 numberOfProposalsVotedOn) = _grantFund.getVoterInfo(distributionId, actor);
I need those values to assert invariant DR3. I'm still trying to figure out the best way to check that invariant

2023-04-03 20:44 UTC, MikeHathaway commented on test/invariants/StandardFinalizeInvariant.t.sol
> +        (, , , uint128 fundsAvailable, , bytes32 topSlateHash) = _grantFund.getDistributionPeriodInfo(distributionId);
removed

2023-04-03 20:45 UTC, MikeHathaway commented on test/invariants/handlers/Handler.sol
> +    // modifier useBlock() {
Updated, with an additional `roll` method. I'm still experimenting with the best approach for getting the system into the correct stage to enable the invariants to actually be checked, while also progressing over time

2023-04-03 20:47 UTC, MikeHathaway commented on test/invariants/StandardScreeningInvariant.t.sol
> +            assertTrue(votesReceived <= 1_000_000_000 * 1e18);
Updated with `totalSupply`. Treating a fuzz test that burns ajna tokens as out of scope

2023-04-03 20:48 UTC, MikeHathaway commented on test/invariants/StandardFundingInvariant.t.sol
> +        // invariant: 10 or less proposals should make it through the screening stage
Updated it as `FS1`. It's essentially the same invariant check as the subsequent assertion, just performed differently

2023-04-03 21:21 UTC, MikeHathaway commented on test/invariants/StandardScreeningInvariant.t.sol
> +            assertTrue(votesReceived >= 0);
We currently allow zero votes. We can potentially start to restrict that.

2023-04-03 22:28 UTC, MikeHathaway commented on test/invariants/StandardScreeningInvariant.t.sol
> +        // invariant: 10 or less proposals should make it through the screening stage
Updated

2023-04-03 22:31 UTC, MikeHathaway commented on test/invariants/StandardScreeningInvariant.t.sol
> +        if (_standardHandler.screeningVotesCast() > 0) {
Was a different check on `SS6` duplicated the comment above it

2023-04-03 22:44 UTC, MikeHathaway commented on test/invariants/StandardFundingInvariant.t.sol
> +        assertTrue(topTenProposals.length <= 10);
Updated to use `require` statements instead.

2023-04-03 22:44 UTC, MikeHathaway commented on test/invariants/StandardFundingInvariant.t.sol
> +            // TODO: check getFundingPowerVotes to see if remaining voting power matches expectations
removed

2023-04-03 23:21 UTC, MikeHathaway commented on test/invariants/INVARIANTS.md
> +- #### Distribution Period:
These invariants aren't checked yet. The list of currently completed invariants is available here: https://www.notion.so/worlds-best-crypto-lending-platform/GrantFund-Standard-Funding-Mechanism-invariant-testing-8b87a0a814a5405aa42f931590d7a332?pvs=4

2023-04-04 12:51 UTC, grandizzy approved these changes
I'm OK with merging in this state as a first iteration, then improve, couple of things noticed
- Log.sol is entirely commented out, not sure if we want to keep it or not (for now I just changed it to prevent compiler warnings)
- `make tests` was executing invariants tests as well, added the `--mt test` to prevent such and minimize GH action time

2023-04-04 18:47 UTC, MikeHathaway commented on test/invariants/INVARIANTS.md
> +   - **GF2**: Treasury should always be less than or equal to the contract's token blance.
Updated accordingly

2023-04-04 18:52 UTC, MikeHathaway commented on test/invariants/base/TestBase.sol
> +        _token = IAjnaToken(0x9a96ec9B57Fb64FbC60B423d1f4da7691Bd35079);
Updated

2023-04-04 18:53 UTC, MikeHathaway commented on test/invariants/handlers/Handler.sol
> +    IAjnaToken        internal  _token;
updated

2023-04-04 19:05 UTC, MikeHathaway commented on test/invariants/StandardFinalizeInvariant.t.sol
> +    function invariant_CS1_CS2_CS3_CS4_CS5() external {
The issue is we need a really high call depth for these tests to work properly, and i need to iterate across both every actor, and every proposal for a lot of these invariant checks. Splitting this into two iterations per invariant would make the test time prohibitive

2023-04-04 19:05 UTC, MikeHathaway commented on foundry.toml
> +fail_on_revert = true  # Fail the test if the contract reverts
I've found that not having `revert=true` slowed me down as problems went unexposed

2023-04-05 13:12 UTC, ith-harvey commented on test/invariants/handlers/Handler.sol
> +        actors = _buildActors(numOfActors_, tokensToDistribute_);
I see -> `Voting power in the screening stage is based upon a snapshot of an address' voting power 33 blocks prior to the screening stage’s start block, `

Agreed, resolving.

2023-04-05 13:13 UTC, ith-harvey approved these changes
LGTM

2023-04-05 16:59 UTC, merged