remove OpenZeppelin Governor inheritance
ajna-finance/ecosystem-coordination pull request #53
Opened 2023-03-17 20:36 UTC by MikeHathaway

- Remove catchall Openzeppelin methods such as `_castVote` and `_getVote` in favor of explicit per-stage methods. This also removes the previous separate code pathway through which votes could occur. Now all voting is channeled through `fundingVote`, `screeningVote`, and `voteExtraordinary`, and proposals are channeled directly to mechanism specific functions like `executeStandard` and `executeExtraordinary`.
- Remove `hasVoted` in favor of mechanism specific methods.
- Added additional view functions for contract state useful for indexers.
- Minimal business logic changes: 
      - Added a revert in `fundingVote` that checks if a proposal is in the top ten coming out of the screening stage.
      - Removed constructor in favor of hardcoding the Ajna token address in Funding.sol. A new external function `fundTreasury` is added in lieu of declaring a fixed amount on contract creation.
      - Rename `checkSlate` to `updateSlate`. Move validation checks into a new `_validateSlate` internal method.

Large gas savings in the execute methods, moderate savings in the voting methods. Contract size is reduced by 7kb.

NEW FUNCTIONS:
```                                                                                                                                                                                     
| src/grants/GrantFund.sol:GrantFund contract |                 |        |        |        |         |                                                                                                             
|---------------------------------------------|-----------------|--------|--------|--------|---------|                                                                                                             
| Deployment Cost                             | Deployment Size |        |        |        |         |                                                                                                             
| 3856971                                     | 19261           |        |        |        |         |                                                                                                             
| Function Name                               | min             | avg    | median | max    | # calls |                                                                                                             
| claimDelegateReward                         | 1459            | 57892  | 58733  | 65533  | 261     |                                                                                                             
| executeExtraordinary                        | 7363            | 34623  | 39844  | 95862  | 13      |                                                                                                             
| executeStandard                             | 8980            | 30066  | 38114  | 47868  | 8       |                                                                                                             
| findMechanismOfProposal                     | 635             | 2067   | 821    | 4747   | 3       |                                                                                                             
| fundTreasury                                | 8086            | 45206  | 44726  | 65956  | 28      |                                                                                                             
| fundingVote                                 | 6177            | 107516 | 106752 | 410843 | 274     |                                                                                                             
| getDelegateReward                           | 3071            | 3561   | 3071   | 5113   | 5       |                                                                                                             
| getDistributionId                           | 351             | 395    | 351    | 2351   | 680     |                                                                                                             
| getDistributionPeriodInfo                   | 1037            | 1587   | 1037   | 5037   | 109     |                                                                                                             
| getExtraordinaryProposalInfo                | 1029            | 1029   | 1029   | 1029   | 6       |                                                                                                             
| getExtraordinaryProposalSucceeded           | 2290            | 2712   | 2788   | 3059   | 3       |                                                                                                             
| getFundedProposalSlate                      | 1111            | 1287   | 1346   | 1346   | 4       |                                                                                                             
| getFundingPowerVotes                        | 15480           | 15668  | 15731  | 15731  | 4       |                                                                                                             
| getFundingVotesCast                         | 1601            | 2341   | 2341   | 3081   | 2       |                                                                                                             
| getMinimumThresholdPercentage               | 493             | 1007   | 764    | 2493   | 6       |                                                                                                             
| getProposalInfo                             | 1038            | 1038   | 1038   | 1038   | 110     |                                                                                                             
| getSlateHash                                | 933             | 941    | 945    | 945    | 3       |                                                                                                             
| getSliceOfNonTreasury                       | 1592            | 2892   | 1592   | 8092   | 5       |                                                                                                             
| getSliceOfTreasury                          | 761             | 1761   | 1761   | 2761   | 2       |                                                                                                             
| getTopTenProposals                          | 1231            | 2495   | 2407   | 3348   | 16      |                                                                                                             
| getVoterInfo                                | 1078            | 1078   | 1078   | 1078   | 5       |                                                                                                             
| getVotesExtraordinary                       | 810             | 7763   | 7775   | 8849   | 1149    |                                                                                                             
| getVotesFunding                             | 2467            | 6662   | 2875   | 11638  | 15      |                                                                                                             
| getVotesScreening                           | 5338            | 5379   | 5372   | 6514   | 536     |                                                                                                             
| hasVotedExtraordinary                       | 717             | 1717   | 1717   | 2717   | 2       |                                                                                                             
| hashProposal                                | 3985            | 3985   | 3985   | 3985   | 110     |                                                                                                             
| proposeExtraordinary                        | 4720            | 64225  | 82362  | 86701  | 19      [...]

2023-03-19 18:28 UTC, ith-harvey reviewed
Regarding TODOs in the PR... I really think either the change is made or not made and we don't continue to insert TODOs at this point in the development process as we are in audit.

2023-03-19 18:28 UTC, ith-harvey commented on src/grants/base/Funding.sol
> +import { IVotes }    from "@oz/governance/utils/IVotes.sol";
for lines 7 - 11 NIT: alignment

2023-03-19 18:28 UTC, ith-harvey commented on src/grants/GrantFund.sol
> +    // TODO: remove token from constructor entirely in favor of constant variable in funding
Can we make a decision on if this TODO should be done? We are at the stage of development where either we "do" or we "don't do" :smile:

2023-03-19 18:28 UTC, ith-harvey commented on src/grants/base/Funding.sol
>  import { ReentrancyGuard } from "@oz/security/ReentrancyGuard.sol";
Why do we import  `ReentrancyGuard`  and does the `Funding contract` inherit `ReentrancyGuard` if it's not used?

2023-03-19 18:28 UTC, ith-harvey commented on src/grants/base/ExtraordinaryFunding.sol
> +        // TODO: check if it's a valid proposal?
I would think that the validation should be done in the submission process

2023-03-19 18:28 UTC, ith-harvey commented on src/grants/base/ExtraordinaryFunding.sol
> +        if (extraordinaryFundingProposals[proposalId_].executed)                                        return ProposalState.Executed;
Suggest initializing a struct in memory -> `proposal` to be used in the `.executed` and `.endBlock` checks so there is only one read from storage.

2023-03-19 18:28 UTC, ith-harvey commented on src/grants/base/Funding.sol
> +    function _execute(
Natspec comments are needed

2023-03-19 18:28 UTC, ith-harvey commented on src/grants/base/Funding.sol
> +        uint256 votes2 = token.getPastVotes(account_, voteStartBlock_);
suggest rename to `votesAtStageStart`

2023-03-19 18:28 UTC, ith-harvey commented on src/grants/base/Funding.sol
> +        uint256 votes1 = token.getPastVotes(account_, snapshot_);
suggest renaming to `votesAtSnapshot`

2023-03-19 18:28 UTC, ith-harvey commented on src/grants/base/StandardFunding.sol
> +        // super.execute(targets_, values_, calldatas_, descriptionHash_);
Does this comment need to exist?

2023-03-19 18:28 UTC, ith-harvey commented on src/grants/base/StandardFunding.sol
> +        // if (status != ProposalState.Succeeded || status != ProposalState.Queued) revert ProposalNotSuccessful();
Do these comments need to exists?

2023-03-19 18:28 UTC, ith-harvey commented on src/grants/base/StandardFunding.sol
> +        if (!_standardFundingVoteSucceeded(proposalId_) || standardFundingProposals[proposalId_].executed) revert ProposalNotSuccessful();
Suggest creating a `proposal` stuct that contains `standardFundingProposals[proposalId_]` to reduce reads from storage. The same struct can be used in 376 too.

2023-03-19 18:28 UTC, ith-harvey commented on src/grants/base/StandardFunding.sol
> +    // TODO: update this to allow usage of arbitrary distribution periods?
Is TODO still needed here?

2023-03-19 18:28 UTC, ith-harvey commented on src/grants/base/StandardFunding.sol
> +    // TODO: update this to allow usage of arbitrary distribution periods?
Is TODO still needed?

2023-03-19 18:28 UTC, ith-harvey commented on test/StandardFunding.t.sol
> +// import { Funding }          from "../src/grants/base/Funding.sol";
still needed?

2023-03-19 18:28 UTC, ith-harvey commented on test/utils/GrantFundTestHelper.sol
> +    /****************/
NIT: Clean up

2023-03-19 21:28 UTC, MikeHathaway commented on src/grants/base/Funding.sol
>  import { ReentrancyGuard } from "@oz/security/ReentrancyGuard.sol";
It's used in StandardFunding and ExtraordinaryFunding. Imported here at the root of the dependency tree

2023-03-19 21:32 UTC, MikeHathaway commented on src/grants/base/Funding.sol
> +        uint256 votes2 = token.getPastVotes(account_, voteStartBlock_);
That function can't be renamed as it's part of ERC20Votes

2023-03-19 21:33 UTC, MikeHathaway commented on src/grants/base/Funding.sol
> +        uint256 votes1 = token.getPastVotes(account_, snapshot_);
Renamed this utility function to `_getVotesAtSnapshotBlocks` for more clarity (plural snapshots)

2023-03-19 21:36 UTC, MikeHathaway commented on src/grants/base/ExtraordinaryFunding.sol
> +        // TODO: check if it's a valid proposal?
There is already validation on proposals being submitted. This comment was more about should we explicitly handle someone trying to get the state of an non-existant proposal, i.e someonewith with proposalId = 0

2023-03-19 21:37 UTC, MikeHathaway commented on test/StandardFunding.t.sol
> +// import { Funding }          from "../src/grants/base/Funding.sol";
Removed

2023-03-20 00:05 UTC, MikeHathaway commented on src/grants/base/ExtraordinaryFunding.sol
> +        if (extraordinaryFundingProposals[proposalId_].executed)                                        return ProposalState.Executed;
Updated accordingly

2023-03-20 00:06 UTC, MikeHathaway commented on src/grants/base/StandardFunding.sol
> +        // super.execute(targets_, values_, calldatas_, descriptionHash_);
Removed

2023-03-20 15:18 UTC, ith-harvey commented on src/grants/base/ExtraordinaryFunding.sol
> +        // TODO: check if it's a valid proposal?
hmm, looking at the `ExtraordinaryFundingProposal` struct it would seem that `startBlock` could be checked. If `0` value then we could revert.

2023-03-20 22:20 UTC, MikeHathaway commented on src/grants/base/StandardFunding.sol
> +        // if (status != ProposalState.Succeeded || status != ProposalState.Queued) revert ProposalNotSuccessful();
Removed

2023-03-20 22:21 UTC, MikeHathaway commented on src/grants/base/StandardFunding.sol
> +        if (!_standardFundingVoteSucceeded(proposalId_) || standardFundingProposals[proposalId_].executed) revert ProposalNotSuccessful();
Updated accordingly

2023-03-20 22:22 UTC, MikeHathaway commented on src/grants/base/StandardFunding.sol
> +    // TODO: update this to allow usage of arbitrary distribution periods?
Removed in https://github.com/ajna-finance/ecosystem-coordination/pull/53/commits/8c93f08a8ce219be01948b777499b904b875df3f

2023-03-20 22:22 UTC, MikeHathaway commented on src/grants/base/StandardFunding.sol
> +    // TODO: update this to allow usage of arbitrary distribution periods?
Removed in https://github.com/ajna-finance/ecosystem-coordination/pull/53/commits/8c93f08a8ce219be01948b777499b904b875df3f

2023-03-21 15:25 UTC, grandizzy requested changes
Overall looks good and it really simplifies logic, had some suggestions on making code a little bit more readable in couple of functions

2023-03-21 15:25 UTC, grandizzy commented on src/grants/base/ExtraordinaryFunding.sol
> +        ExtraordinaryFundingProposal memory proposal = extraordinaryFundingProposals[proposalId_];
I think rewritting function like this could be clearer

```Solidity
    /**
     * @notice Check if a proposal for extraordinary funding has succeeded.
     * @param  proposalId_ The ID of the proposal being checked.
     * @return Boolean indicating whether the proposal has succeeded.
     */
    function _extraordinaryProposalSucceeded(
        uint256 proposalId_,
        uint256 tokensRequested_
    ) internal view returns (bool) {
        uint256 votesReceived          = uint256(extraordinaryFundingProposals[proposalId_].votesReceived);
        uint256 minThresholdPercentage = _getMinimumThresholdPercentage();

        return
            // succeeded if proposal's votes received doesn't exceed the minimum threshold required
            (uint256(votesReceived) >= tokensRequested_ + _getSliceOfNonTreasury(minThresholdPercentage))
            &&
            // succeeded if tokens requested are available for claiming from the treasury
            (tokensRequested_ <= _getSliceOfTreasury(Maths.WAD - minThresholdPercentage))
        ;
    }
```

2023-03-21 15:25 UTC, grandizzy commented on src/grants/base/ExtraordinaryFunding.sol
> +    function _getVotesExtraordinary(address account_, uint256 proposalId_) internal view returns (uint256 votes_) {
let's add comment for this function too. also can be better written IMO as 
```Solidity
    function _getVotesExtraordinary(address account_, uint256 proposalId_) internal view returns (uint256 votes_) {
        if (proposalId_ == 0) revert ExtraordinaryFundingProposalInactive();

        uint256 startBlock = extraordinaryFundingProposals[proposalId_].startBlock;

        votes_ = _getVotesAtSnapshotBlocks(
            account_,
            startBlock - VOTING_POWER_SNAPSHOT_DELAY,
            startBlock
        );
    }
```

2023-03-21 15:25 UTC, grandizzy commented on src/grants/base/ExtraordinaryFunding.sol
> +    function getExtraordinaryProposalSucceeded(uint256 proposalId_) external view returns (bool) {
let's add comment for the function

2023-03-21 15:25 UTC, grandizzy commented on src/grants/base/ExtraordinaryFunding.sol
> +    function getVotesExtraordinary(address account_, uint256 proposalId_) external view returns (uint256 votes_) {
let's add comment for the function

2023-03-21 15:25 UTC, grandizzy commented on src/grants/GrantFund.sol
>      constructor(IVotes token_, uint256 treasury_)
if `treasury_` is passed in constructor, does this mean that we have to fund the contract with the exact amount as `treasury_` value? is there any chance we decide to fund in multiple steps?
can we add comments for constructor params to make things clear?

2023-03-21 15:25 UTC, grandizzy commented on src/grants/base/Funding.sol
> +    function hashProposal(
should this be declared in interface and overriden / inheritdoc here? Any reason visibility is public and not external?

2023-03-21 15:25 UTC, grandizzy commented on src/grants/base/StandardFunding.sol
> +    function getVotesScreening(uint24 distributionId_, address account_) external view returns (uint256 votes_) {
should we declare these functions in interfaces and override / inheritdoc them here?

2023-03-21 15:25 UTC, grandizzy commented on src/grants/base/StandardFunding.sol
> +    function _getVotesFunding(uint24 distributionId_, address account_) internal view returns (uint256 votes_) {
since we call this one from `fundingVote` only where we already load `QuarterlyDistribution` and `QuadraticVoter` structs, I suggest to change to
```Solidity
    function _getVotesFunding(
        uint256 votingPower_,
        uint256 remainingVotingPower_,
        uint256 endBlock_
    ) internal view returns (uint256 votes_) {
        // voter has already allocated some of their budget this period
        if (votingPower_ != 0) {
            votes_ = remainingVotingPower_;
        }
        // voter hasn't yet called _castVote in this period
        else {
            uint256 screeningStageEndBlock = _getScreeningStageEndBlock(endBlock_);
            votes_ = Maths.wpow(
            _getVotesAtSnapshotBlocks(
                account_,
                screeningStageEndBlock - VOTING_POWER_SNAPSHOT_DELAY,
                screeningStageEndBlock
            ), 2);
        }
    }
``` 

and pass them as params instead reloading again the structs. In `getVotesFunding` external function we can load structs / pass these values to `_getVotesFunding` view function

2023-03-21 15:25 UTC, grandizzy commented on src/grants/base/StandardFunding.sol
> +        QuarterlyDistribution memory currentDistribution = distributions[distributionId_];
I suggest to
```Solidity
    function _getVotesScreening(uint24 distributionId_, address account_) internal view returns (uint256 votes_) {
        uint256 startBlock = distributions[distributionId_].startBlock;

        // calculate voting weight based on the number of tokens held at the snapshot blocks of the screening stage
        votes_ = _getVotesAtSnapshotBlocks(
            account_,
            startBlock - VOTING_POWER_SNAPSHOT_DELAY,
            startBlock
        );
    }
```

2023-03-21 18:46 UTC, MikeHathaway commented on src/grants/base/ExtraordinaryFunding.sol
> +        ExtraordinaryFundingProposal memory proposal = extraordinaryFundingProposals[proposalId_];
Updated accordingly

2023-03-21 18:54 UTC, MikeHathaway commented on src/grants/base/ExtraordinaryFunding.sol
> +    function _getVotesExtraordinary(address account_, uint256 proposalId_) internal view returns (uint256 votes_) {
Added natspec and updated accordingly

2023-03-21 18:56 UTC, MikeHathaway commented on src/grants/base/Funding.sol
> +    function hashProposal(
It's used internally to create a proposalId out of inputs. I figured it would be useful to also have it available to external callers. I can switch this to use internal/external methods instead

2023-03-21 18:58 UTC, MikeHathaway commented on src/grants/base/StandardFunding.sol
> +    function getVotesScreening(uint24 distributionId_, address account_) external view returns (uint256 votes_) {
Updated accordingly

2023-03-21 18:59 UTC, MikeHathaway commented on src/grants/base/StandardFunding.sol
> +        QuarterlyDistribution memory currentDistribution = distributions[distributionId_];
Updated accordingly

2023-03-21 19:04 UTC, MikeHathaway commented on src/grants/GrantFund.sol
>      constructor(IVotes token_, uint256 treasury_)
Yes we would need to fund the contract with that exact amount. We should be able to transfer the tokens to the contract in multiple steps, however. I will add comments.

I was considering removing the token parameter entirely and instantiating it on the fly based upon a hard coded ajna token address in Funding.sol instead

2023-03-21 19:14 UTC, grandizzy commented on src/grants/GrantFund.sol
>      constructor(IVotes token_, uint256 treasury_)
That could be better, let's consider the case where treasury is set at contract deployment time at 1mm but contract gets only 10k funding in first round. Does this impact grant fund logic (as in are places where we calculate things for 1mm but they actually should be calculated for contract balance of 10k)? Do we have unit test for this situation?

2023-03-21 19:22 UTC, grandizzy commented on src/grants/GrantFund.sol
>      constructor(IVotes token_, uint256 treasury_)
Wouldn't be better to have a `fundTreasury(ajnaAmount)` function that would transfer the `ajnaAmount` from sender to contract and increment treasury state var by `ajnaAmount` in same tx?

2023-03-21 19:23 UTC, MikeHathaway commented on src/grants/GrantFund.sol
>      constructor(IVotes token_, uint256 treasury_)
This is a good question. The only place it would really have an impact are if there were insufficient tokens and the contract would revert if someone tried to execute a proposal or `claimDelegateReward`. We use the treasury value instead of the contract's token balance. We don't currently have a unit test for this situation, but I will add it

2023-03-21 19:30 UTC, grandizzy commented on src/grants/GrantFund.sol
>      constructor(IVotes token_, uint256 treasury_)
👍

2023-03-21 19:41 UTC, MikeHathaway commented on src/grants/base/StandardFunding.sol
> +    function _getVotesFunding(uint24 distributionId_, address account_) internal view returns (uint256 votes_) {
Updated accordingly

2023-03-21 19:57 UTC, MikeHathaway commented on src/grants/base/ExtraordinaryFunding.sol
> +    function getExtraordinaryProposalSucceeded(uint256 proposalId_) external view returns (bool) {
Added

2023-03-21 19:57 UTC, MikeHathaway commented on src/grants/base/ExtraordinaryFunding.sol
> +    function getVotesExtraordinary(address account_, uint256 proposalId_) external view returns (uint256 votes_) {
Added

2023-03-21 19:58 UTC, MikeHathaway commented on src/grants/base/Funding.sol
> +    function _execute(
Added

2023-03-21 20:50 UTC, MikeHathaway commented on src/grants/base/ExtraordinaryFunding.sol
> +        // TODO: check if it's a valid proposal?
Removed TODO entirely. Since this is primarily used for analytics, the existing validation checks around handling proposals are sufficient

2023-03-21 23:43 UTC, MikeHathaway commented on src/grants/GrantFund.sol
>      constructor(IVotes token_, uint256 treasury_)
Added `fundTreasury` method as recommended in [e1de8ef4341f5e3f940105a89890ee4914fbf744](https://github.com/ajna-finance/ecosystem-coordination/pull/53/commits/e1de8ef4341f5e3f940105a89890ee4914fbf744)

2023-03-21 23:44 UTC, MikeHathaway commented on src/grants/GrantFund.sol
> +    // TODO: remove token from constructor entirely in favor of constant variable in funding
Removed constructor entirely in https://github.com/ajna-finance/ecosystem-coordination/pull/53/commits/e1de8ef4341f5e3f940105a89890ee4914fbf744

2023-03-22 06:13 UTC, grandizzy requested changes

2023-03-22 06:13 UTC, grandizzy commented on src/grants/GrantFund.sol
> +    function fundTreasury(uint256 fundingAmount_) external override returns (uint256) {
I think this makes sense now. I'm concerned though about one directly sending Ajna tokens to the contract which will be accounted in balances but not in treasury (and probably messing the funding logic?), is there a way to revert on direct transfer to contract? Or if there's a way to callback and automatically increment treasury on ERC20 transfer to contract?

2023-03-22 06:13 UTC, grandizzy commented on src/grants/GrantFund.sol
> +        return treasury;
don't think we have to return treasury from here, is not used anywhere and one could just call the view function to check new treasury

2023-03-22 06:13 UTC, grandizzy commented on src/grants/base/StandardFunding.sol
> +        QuadraticVoter        storage voter               = quadraticVoters[currentDistributionId][msg.sender];
suggest to do a `uint24 distribution = currentDistributionId` and use in `distributions[distribution]` and `quadraticVoters[distribution][msg.sender]` to avoid multiple reading from storage
same in `if (proposal.distributionId != distribution) revert InvalidVote();` and line 530

2023-03-22 06:13 UTC, grandizzy commented on src/grants/base/StandardFunding.sol
> +        QuadraticVoter        storage voter               = quadraticVoters[currentDistributionId][msg.sender];
same in `startNewDistributionPeriod` function, `currentDistributionId` is read 6 times from storage

2023-03-22 06:13 UTC, grandizzy commented on src/grants/GrantFund.sol
> +        token.safeTransferFrom(msg.sender, address(this), fundingAmount_);
I'd suggest moving this before `FundTreasury` event emit so we'll have `Transfer` first and then `FundTreasury`

2023-03-22 11:31 UTC, grandizzy commented on src/grants/GrantFund.sol
> +    function fundTreasury(uint256 fundingAmount_) external override returns (uint256) {
On the other hand checking thew code we're not relying on `balanceOf` anywhere in contract, so we can just consider tokens sent directly to contract lost?

2023-03-22 11:56 UTC, grandizzy commented on src/grants/GrantFund.sol
> +        return treasury;
proposed in https://github.com/ajna-finance/ecosystem-coordination/pull/54

2023-03-22 11:56 UTC, grandizzy commented on src/grants/base/StandardFunding.sol
> +        QuadraticVoter        storage voter               = quadraticVoters[currentDistributionId][msg.sender];
proposed in https://github.com/ajna-finance/ecosystem-coordination/pull/54

2023-03-22 11:56 UTC, grandizzy commented on src/grants/GrantFund.sol
> +        token.safeTransferFrom(msg.sender, address(this), fundingAmount_);
proposed in https://github.com/ajna-finance/ecosystem-coordination/pull/54

2023-03-22 12:01 UTC, grandizzy commented on src/grants/GrantFund.sol
> +        token.safeTransferFrom(msg.sender, address(this), fundingAmount_);
hm, actually this triggers slither warning so I put it back ... strange order of events though

2023-03-22 19:45 UTC, grandizzy approved these changes
lgtm

2023-03-22 20:38 UTC, ith-harvey approved these changes
LGTM

2023-03-22 22:23 UTC, merged