Q-AJN-5: Missing Input Validation
ajna-finance/ecosystem-coordination pull request #82
Opened 2023-05-10 21:09 UTC by MikeHathaway

# Description of change
## High level
* Add additional external input validations
  * Update `voteExtraordinary`, `fundingVote`, `screeningVote` to check that each successive vote being cast is using non 0 voting power.
  * Update `_validateSlate` to check that a slate contains a proposal, and that each proposal has >0 funding votes received: https://github.com/code-423n4/2023-05-ajna-findings/issues/465
  * Also fixes a bug where a proposal could be executed even if it received no funding votes by changing a check to `<=`
  * Update invariant tests for the new assertions.
  * Add validation to calldata length as suggested in: https://github.com/code-423n4/2023-05-ajna-findings/issues/280

https://github.com/code-423n4/2023-05-ajna-findings/issues/465

2023-05-11 12:47 UTC, prat-gpt approved these changes
LGTM

2023-05-11 19:23 UTC, grandizzy requested changes

2023-05-11 19:23 UTC, grandizzy commented on src/grants/base/StandardFunding.sol
> +        // check that there is a proposal in the slate
suggest better move this at line 428 in same if clause and before checking if it has duplicates

2023-05-11 19:23 UTC, grandizzy commented on src/grants/base/StandardFunding.sol
> +            if (voteParams_[i].votesUsed == 0) revert InvalidVote();
Same as above, better check before findProposalIndex

2023-05-11 19:28 UTC, grandizzy commented on src/grants/base/StandardFunding.sol
> +            // block proposals that recieve no positive funding votes from entering a finalized slate
Missed that one, also better to do the check in same line 441 before even searching the proposal index

2023-05-12 01:12 UTC, ith-harvey reviewed
They suggested that `description_` is checked for non-zero, didn't see that included in PR.

2023-05-12 17:51 UTC, MikeHathaway commented on src/grants/base/StandardFunding.sol
> +        // check that there is a proposal in the slate
Updated accordingly

2023-05-12 17:56 UTC, MikeHathaway commented on src/grants/base/StandardFunding.sol
> +            if (voteParams_[i].votesUsed == 0) revert InvalidVote();
updated

2023-05-12 17:56 UTC, MikeHathaway commented on src/grants/base/StandardFunding.sol
> +            // block proposals that recieve no positive funding votes from entering a finalized slate
updated

2023-05-12 19:54 UTC, MikeHathaway commented
> They suggested that `description_` is checked for non-zero, didn't see that included in PR.

Added

2023-05-12 20:30 UTC, grandizzy approved these changes

2023-05-12 20:47 UTC, merged