CodeArena-413: Delegate Reward Distribution
ajna-finance/ecosystem-coordination pull request #99
Opened 2023-05-30 19:09 UTC by MikeHathaway

# Description of change
## High level
* Increase the fairness of delegation rewards distribution.
  * No vulnerabilities, just an enhancement to the reward distribution. We currently give a disproportionate amount of rewards to larger voters.

# Description of bug or vulnerability and solution
* https://github.com/code-423n4/2023-05-ajna-findings/issues/413
* https://github.com/code-423n4/2023-05-ajna-findings/issues/333
* https://github.com/code-423n4/2023-05-ajna-findings/issues/293
* https://github.com/code-423n4/2023-05-ajna-findings/issues/191

2023-05-31 18:23 UTC, mattcushman commented on src/grants/GrantFund.sol
> +        uint256 rootVotingPowerAllocatedByDelegatee = Math.sqrt(votingPowerAllocatedByDelegatee) * 1e9;
can we try instead:
`uint256 rootVotingPowerAllocatedByDelegatee = Math.sqrt(votingPowerAllocatedByDelegatee * 1e18);`  That should have less rounding error

2023-05-31 19:19 UTC, mattcushman commented on src/grants/GrantFund.sol
> +            (Math.sqrt(uint256(cumulativeVotePowerUsed)) - Math.sqrt(uint256(voterPowerUsedPreVote))) * 1e9;
this should be changed too

2023-05-31 19:35 UTC, MikeHathaway commented on src/grants/GrantFund.sol
> +            (Math.sqrt(uint256(cumulativeVotePowerUsed)) - Math.sqrt(uint256(voterPowerUsedPreVote))) * 1e9;
Updated accordingly

2023-05-31 19:41 UTC, MikeHathaway commented on test/unit/StandardFunding.t.sol
> -            uint256 reward = Maths.wdiv(Maths.wmul(gbc, Maths.wpow(votes[i], 2)), totalBudgetAllocated) / 10;
Due to rounding issues, we had to switch to using GrantFund state as opposed to calculating votes separately.

2023-05-31 19:51 UTC, mattcushman requested changes

2023-05-31 19:51 UTC, mattcushman commented on src/grants/GrantFund.sol
>              ) / 10;
Even more accurate:

```          
rewards_ = Maths.mulDiv(
                    currentDistribution_.fundsAvailable,
                    rootVotingPowerAllocatedByDelegatee,
                10 * currentDistribution_.fundingVotePowerCast
            );
```

However, I have a question:  is `currentDistribution_.fundingVotePowerCast` the squared quantity?  I think we want the square root of that too, otherwise we will allocate very little of the treasury.

We should have a test that tries to redeem all rewards and see what the percentage is?

2023-05-31 21:06 UTC, MikeHathaway commented on src/grants/GrantFund.sol
>              ) / 10;
Updated to use `mulDiv` instead. Yes that is the squared quantity.

I'm working on an invariant tests for DR5 which should provide some assurance.

2023-06-01 18:49 UTC, ith-harvey reviewed
reviewing now, curious if you could share some of the reasons why open zeppelin's `sqrt` was better than Uniswaps, I recall you mentioning it had to do with precision loss if I'm not mistaken?

2023-06-01 18:51 UTC, MikeHathaway commented
> reviewing now, curious if you could share some of the reasons why open zeppelin's `sqrt` was better than Uniswaps, I recall you mentioning it had to do with precision loss if I'm not mistaken?

Yeah seemed to be slightly better precision wise, and also more widely used.

2023-06-01 18:52 UTC, MikeHathaway commented on test/invariants/INVARIANTS.md
> +    <!-- TODO: move these into separate 'Proposal invariants:' section -->
I was going to follow this PR up with another PR with additional invariant improvements that resolves these TODOs

2023-06-01 19:22 UTC, ith-harvey requested changes
Looks good, had  couple comments / qs

2023-06-01 19:22 UTC, ith-harvey commented on src/grants/GrantFund.sol
> +        uint256 rootVotingPowerAllocatedByDelegatee = Math.sqrt(votingPowerAllocatedByDelegatee * 1e18);
NIT: add an additional comment about this line explaining we take the square root of voting power so that the rewards are distributed linearly accross delegates.

2023-06-01 19:22 UTC, ith-harvey commented on src/grants/GrantFund.sol
> +        // multiply by 1e9 to maintain precision.
where do we multiply by `1e9`?

2023-06-01 19:22 UTC, ith-harvey commented on test/invariants/INVARIANTS.md
> +    - **DR5**: Cumulative rewards claimed should be within 99.99% -or- 0.01 AJNA tokens of all available delegation rewards.
NIT: either keep both of these values in percents or decimals.

2023-06-01 19:22 UTC, ith-harvey commented on test/invariants/INVARIANTS.md
>      - **DR3**: Delegation rewards are proportional to voters funding power allocated in the funding stage.
Shouldn't this be changed to:
```
- **DR3**: Delegation rewards are equal to the square root of delegetee's funding power allocated in the funding stage.
```

2023-06-01 19:22 UTC, ith-harvey commented on test/unit/Maths.t.sol
> +    function testSqrt() external {
Nice! Shouldn't we also have a test here for `Math.mulDiv()`?

2023-06-01 19:22 UTC, ith-harvey commented on test/unit/StandardFunding.t.sol
> -            uint256 reward = Maths.wdiv(Maths.wmul(gbc, Maths.wpow(votes[i], 2)), totalBudgetAllocated) / 10;
Do you think there is value in calculating separatley like you had orginally but then setting a diff (so we can measure what kind of rounding we are comfortable with)?

This may be a good idea to add to an invariant...

2023-06-01 19:22 UTC, ith-harvey requested changes
Looks good, had  couple comments / qs

2023-06-01 19:26 UTC, MikeHathaway commented on test/unit/Maths.t.sol
> +    function testSqrt() external {
It's part of OpenZeppelin library and is tested extensively over there

2023-06-01 19:26 UTC, MikeHathaway commented on src/grants/GrantFund.sol
> +        // multiply by 1e9 to maintain precision.
it's done implicitly when we premultiply by 1e18. I'll update the comment to be clearer.

2023-06-01 19:27 UTC, MikeHathaway commented on test/invariants/INVARIANTS.md
>      - **DR3**: Delegation rewards are proportional to voters funding power allocated in the funding stage.
I don't think so, as since we're taking the square root of both sides it's really just their proportion of all funding power. But the sentence could be clearer

2023-06-01 19:28 UTC, MikeHathaway commented on test/unit/StandardFunding.t.sol
> -            uint256 reward = Maths.wdiv(Maths.wmul(gbc, Maths.wpow(votes[i], 2)), totalBudgetAllocated) / 10;
That's the idea behind `invariant DR5`. Invariant tests are generally higher value so was planning on investing more time into those

2023-06-01 19:29 UTC, MikeHathaway commented on src/grants/GrantFund.sol
> +        uint256 rootVotingPowerAllocatedByDelegatee = Math.sqrt(votingPowerAllocatedByDelegatee * 1e18);
Will update

2023-06-01 20:22 UTC, ith-harvey commented on test/unit/Maths.t.sol
> +    function testSqrt() external {
OK... by that logic why do we test the `Math.sqrt()` method here then? Not enough testing in OpenZep?

2023-06-01 20:23 UTC, ith-harvey commented on test/unit/StandardFunding.t.sol
> +import { console }   from "@std/console.sol";
suggest remove

2023-06-01 20:24 UTC, ith-harvey commented on test/unit/StandardFunding.t.sol
> -            uint256 reward = Maths.wdiv(Maths.wmul(gbc, Maths.wpow(votes[i], 2)), totalBudgetAllocated) / 10;
k, like the idea of a diff invariant to handle rounding. Helps me sleep :pray:

2023-06-01 20:28 UTC, MikeHathaway commented on test/unit/Maths.t.sol
> +    function testSqrt() external {
We were trying to get visibility into the precision of the sqrt function so we added this unit test. It's helpful to ensuring precise delegation rewards. We already know mulDiv > wmul/wdiv

2023-06-01 20:31 UTC, MikeHathaway commented on test/unit/StandardFunding.t.sol
> +import { console }   from "@std/console.sol";
removed

2023-06-01 21:05 UTC, ith-harvey approved these changes
Looks good, thanks mike

2023-06-02 10:31 UTC, grandizzy approved these changes
LGTM

2023-06-02 13:05 UTC, mattcushman approved these changes
lgtm

2023-06-02 14:47 UTC, merged